/* eslint-disable no-unused-vars */
var CONCERT_DATA = {
  playlistUrl: 'https://youtube.com/playlist?list=PLl1nGeQ1UIbw0lAfx8bVlPcF61i_jV5Ec',

  celine: [
    { videoId: 'vGjnM-nShNs', title: 'Hits Medley (Taking Chances World Tour)', duration: '10:04', date: '2008', views: '142M', category: 'Celine Dion', description: 'Official VEVO — Taking Chances World Tour' },
    { videoId: 'DNyKDI-inps', title: 'My Heart Will Go On (Taking Chances)', duration: '5:10', date: '2008', views: '120M', category: 'Celine Dion', description: 'Official VEVO — Las Vegas' },
    { videoId: 'a1Y73sPHKxw', title: 'The Power of Love (Taking Chances)', duration: '3:32', date: '2008', views: '75M', category: 'Celine Dion', description: 'Official VEVO' },
    { videoId: 'p4W_Mlk1EO4', title: 'All By Myself (Taking Chances)', duration: '5:26', date: '2008', views: '57M', category: 'Celine Dion', description: 'Official VEVO' },
    { videoId: 'X2nUfu3iXkQ', title: "My Heart Will Go On – Billboard Music Awards 2017", duration: '5:11', date: '2017', views: '17M', category: 'Celine Dion', description: 'Official VEVO' },
    { videoId: 'wG2s0fTacP0', title: "It's All Coming Back To Me Now – Live in Las Vegas", duration: '7:11', date: '2007', views: '13M', category: 'Celine Dion', description: 'Official VEVO — A New Day' },
    { videoId: '5c_BQnTQ6rM', title: "The Power of Love & I'm Alive – Elie Saab Riyadh 2024", duration: '14:31', date: '2024', views: '5M', category: 'Celine Dion', description: '4K comeback performance' },
    { videoId: 'GBo2e4V5k8I', title: 'Because You Loved Me – Official Live HD', duration: '5:45', date: '2007', views: '6.2M', category: 'Celine Dion', description: 'Official live' },
    { videoId: 'vKGMxEMjvR8', title: 'Live in Manila 2018 – Full Concert', duration: '1:58:08', date: '2018', views: '2.7M', category: 'Celine Dion', description: 'Full concert HD' },
    { videoId: 'f5N-Eio1iZE', title: 'A New Day – Live in Las Vegas 2007 Full Concert', duration: '1:33:07', date: '2007', views: '2.2M', category: 'Celine Dion', description: 'Full concert' },
  ],

  shakira: [
    { videoId: 'pILCn6VO_RU', title: 'Super Bowl LIV Full Halftime Show', duration: '14:21', date: '2020', views: '300M+', category: 'Shakira', description: 'NFL Official' },
    { videoId: 'BQcgrdkoGbc', title: 'Super Bowl LIV Shakira Only | 4K', duration: '6:14', date: '2020', views: '5M', category: 'Shakira', description: '4K cut' },
    { videoId: 'P1jGg5nMoyc', title: 'Copa América 2024 Finals Performance', duration: '8:09', date: '2024', views: '25M', category: 'Shakira', description: 'Live finals' },
    { videoId: 'uVTifWo9uH0', title: 'MTV VMAs 2023 Video Vanguard', duration: '10:17', date: '2023', views: '25M', category: 'Shakira', description: 'Award performance' },
    { videoId: 'CT8xMunS608', title: 'La La La / Waka Waka – El Dorado Tour', duration: '7:21', date: '2018', views: '102M', category: 'Shakira', description: 'World Tour' },
    { videoId: 'uyAREe7CQDc', title: 'El Dorado World Tour | Full Concert', duration: '2:02:07', date: '2018', views: '2M', category: 'Shakira', description: 'Full 4K' },
    { videoId: 'onlZQ0jKUZc', title: 'Antología (El Dorado World Tour - Live)', duration: '4:01', date: '2018', views: '28M', category: 'Shakira', description: 'Live' },
    { videoId: 'IHqUiOvjlC0', title: 'Live From Paris | Full Concert', duration: '1:39:55', date: '2011', views: '3M', category: 'Shakira', description: 'Full concert' },
    { videoId: 'OZUzX4kbtDU', title: 'Hips Don\'t Lie (Live) ft. Wyclef – Official', duration: '7:11', date: '2006', views: '98M', category: 'Shakira', description: 'Official' },
    { videoId: '2Ndra-1Pwug', title: 'Hips Don\'t Lie – LMYNL Tour w/ Wyclef', duration: '4:55', date: '2024', views: '69M', category: 'Shakira', description: 'World Tour' },
  ],

  dance: [
    { videoId: 'sOnqjkJTMaA', title: 'Thriller (Official 4K) — Greatest Music Video Ever', duration: '13:42', date: '1984', views: '1.1B', category: 'Dance', description: 'Michael Jackson — Library of Congress, VEVO 4K' },
    { videoId: 'ZXmjhRkPVFc', title: 'Billie Jean — First Moonwalk Ever (Motown 25)', duration: '4:50', date: '1983', views: '180M', category: 'Dance', description: 'Michael Jackson — HD 60fps, historic' },
    { videoId: 'FdX8_GyNycQ', title: 'Billie Jean — 30th Anniversary 4K', duration: '8:00', date: '2001', views: '45M', category: 'Dance', description: 'Michael Jackson — Madison Square Garden 4K' },
    { videoId: 'RU52dSNrgCg', title: 'Single Ladies (Put a Ring on It) — 4K Remaster', duration: '3:20', date: '2008', views: '1B+', category: 'Dance', description: 'Beyoncé — Official VEVO 4K' },
    { videoId: 'Ye2OMov9dQs', title: 'Waka Waka — FIFA World Cup 2010 Live', duration: '3:09', date: '2010', views: '5M+', category: 'Dance', description: 'Shakira — Official FIFA, HD sound' },
    { videoId: 'Gs069dndIYk', title: 'September — Official HD', duration: '3:36', date: '2013', views: '864M', category: 'Dance', description: 'Earth, Wind & Fire — Official HD audio' },
    { videoId: 'G3lAM_L3jR0', title: 'The Babbitt and the Bromide — Astaire & Kelly', duration: '7:18', date: '1946', views: '1.5M', category: 'Dance', description: 'Fred Astaire & Gene Kelly — Classic Hollywood' },
    { videoId: 'ru0K8uYEZWw', title: "Can't Stop the Feeling! — Official Video", duration: '3:56', date: '2016', views: '1.7B', category: 'Dance', description: 'Justin Timberlake — Grammy winner, HD' },
    { videoId: 'LjiUn1MZZwQ', title: 'Yeah! — Live HD Truth Tour', duration: '5:00', date: '2005', views: '1.7M', category: 'Dance', description: 'Usher ft. Lil Jon — Atlanta' },
    { videoId: 'OPf0YbXqDm0', title: 'Uptown Funk — Official Video', duration: '4:30', date: '2014', views: '4.7B', category: 'Dance', description: 'Mark Ronson ft. Bruno Mars — VEVO HD' },
    { videoId: 'lYBUbBu4W08', title: 'Happy — Official Video (24 Hours)', duration: '4:14', date: '2013', views: '1.4B', category: 'Dance', description: 'Pharrell Williams — Official HD' },
    { videoId: '4fndeDfaWCg', title: 'Get Lucky — Grammy 2014 Live', duration: '5:30', date: '2014', views: '25M+', category: 'Dance', description: 'Daft Punk, Pharrell, Stevie Wonder, Nile Rodgers' },
    { videoId: '09R8_2nJtjg', title: 'Blurred Lines — Live (HD)', duration: '4:15', date: '2013', views: '120M', category: 'Dance', description: 'Robin Thicke ft. Pharrell, T.I.' },
    { videoId: 'OAwaNWGLM0c', title: 'Rhythm Nation — Official Video', duration: '4:26', date: '1989', views: '37M', category: 'Dance', description: 'Janet Jackson — Iconic choreography, VEVO' },
    { videoId: 'JGwWNGJdvx8', title: 'Shape of You — Official Video', duration: '3:53', date: '2017', views: '5.8B', category: 'Dance', description: 'Ed Sheeran — VEVO HD' },
    { videoId: 'CevxZvSJLk8', title: 'Uptown Funk — Live Grammys 2015', duration: '4:30', date: '2015', views: '80M', category: 'Dance', description: 'Bruno Mars & Mark Ronson' },
  ],

  classics: [
    { videoId: 'ajbJqfNS0aA', title: 'Born to Run — Live Hammersmith Odeon 1975', duration: '4:07', date: '1975', views: '705K', category: 'Bruce Springsteen', description: 'E Street Band — Official VEVO' },
    { videoId: 'IxuThNgl3YA', title: 'Born to Run — Official Video', duration: '5:33', date: '2009', views: '64M', category: 'Bruce Springsteen', description: 'Official VEVO' },
    { videoId: '129kuDCQtHs', title: 'Dancing in the Dark — Official Video', duration: '4:05', date: '1984', views: '480M', category: 'Bruce Springsteen', description: 'Official VEVO' },
    { videoId: 'b-VAxGJdJeQ', title: 'Twist & Shout — Ed Sullivan Show 1964', duration: '2:35', date: '1964', views: '76M', category: 'The Beatles', description: 'Historic TV performance' },
    { videoId: 'jenWdylTtzs', title: 'I Want To Hold Your Hand — Ed Sullivan 1964', duration: '2:30', date: '1964', views: '118M', category: 'The Beatles', description: 'Official VEVO' },
    { videoId: 'NCtzkaL2t_Y', title: "Don't Let Me Down — Rooftop Concert 1969", duration: '3:35', date: '1969', views: '557M', category: 'The Beatles', description: 'Apple rooftop — Official' },
    { videoId: 'jInxwU27G30', title: 'Live at Shea Stadium 1965 — 4K', duration: '15:00', date: '1965', views: '25M', category: 'The Beatles', description: 'Historic stadium concert' },
    { videoId: '6inwzOooXRU', title: '(They Long to Be) Close to You', duration: '3:40', date: '1970', views: '45M', category: 'The Carpenters', description: 'Karen Carpenter — Official' },
    { videoId: 'YpW6VzBLCLQ', title: "We've Only Just Begun — Grammy's 1971", duration: '3:05', date: '1971', views: '12M', category: 'The Carpenters', description: 'Live Grammy performance' },
    { videoId: 'unfzfe8f9NI', title: 'Mamma Mia — Official Video', duration: '3:30', date: '2009', views: '360M', category: 'ABBA', description: 'Official VEVO HD' },
    { videoId: '4XJBNJ2wq0Y', title: 'Waterloo — Eurovision 1974', duration: '3:05', date: '1974', views: '4.5M+', category: 'ABBA', description: 'Official AbbaVEVO — Eurovision winner' },
    { videoId: '16y1AkoZkmQ', title: 'Rasputin — Sopot Festival 1979', duration: '5:51', date: '1979', views: '742M', category: 'Boney M', description: 'Official BoneyMVEVO' },
    { videoId: 'l3QxT-w3WMo', title: 'Rivers of Babylon — Sopot Festival 1979', duration: '4:20', date: '1979', views: '375M', category: 'Boney M', description: 'Official BoneyMVEVO' },
    { videoId: '4G-YQA_bsOU', title: 'Bridge Over Troubled Water — Official', duration: '4:52', date: '1970', views: '120M', category: 'Simon & Garfunkel', description: 'Official VEVO' },
    { videoId: 'NAEppFUWLfc', title: 'The Sound of Silence — Central Park 1981', duration: '3:20', date: '1981', views: '185M', category: 'Simon & Garfunkel', description: 'Concert in Central Park — Official' },
    { videoId: '1t8kAbUg4t4', title: 'My Way — Official', duration: '4:35', date: '1969', views: '11M', category: 'Frank Sinatra', description: 'Classic crooner' },
    { videoId: 'S_R2gSvjE0s', title: 'Unforgettable — Official', duration: '3:12', date: '1951', views: '25M', category: 'Nat King Cole', description: 'Remastered HD' },
    { videoId: 'LK4pmJQ6zgM', title: 'Moon River — 1961', duration: '2:45', date: '1961', views: '3.1M', category: 'Andy Williams', description: 'Signature song' },
    { videoId: 'EvB_9Sj056M', title: "That's Amore — Official", duration: '3:08', date: '1953', views: '35M', category: 'Dean Martin', description: 'Classic crooner' },
    { videoId: 'Vg0Bn5Z3P7I', title: 'Strangers in the Night — Live', duration: '2:45', date: '1966', views: '15M', category: 'Frank Sinatra', description: 'Grammy Record of the Year' },
    { videoId: 'FaCbSLZ5nYo', title: 'White Christmas — Official', duration: '3:02', date: '1942', views: '55M', category: 'Bing Crosby', description: 'All-time classic' },
    { videoId: 'VpE2pnIzGmM', title: 'I Left My Heart in San Francisco — Live', duration: '2:55', date: '1962', views: '8M', category: 'Tony Bennett', description: 'Signature song, Grammy winner' },
  ],

  football: [
    { videoId: 'Da_CDPRG2j0', title: "Maradona — Goal of the Century", duration: '2:15', date: '1986', views: '3.2M', category: 'Football', description: 'Argentina vs England — FIFA' },
    { videoId: 'KbHSqABJF_0', title: "Messi — Solo vs Getafe", duration: '1:30', date: '2007', views: '25M', category: 'Football', description: 'Barcelona Copa del Rey' },
    { videoId: 'WLgMRyRjVrI', title: 'Roberto Carlos — Free Kick vs France', duration: '1:20', date: '1997', views: '15M', category: 'Football', description: 'Physics-defying curl' },
    { videoId: 'Ly3mSsHg9T0', title: 'Van Basten — Euro 1988 Volley', duration: '0:41', date: '1988', views: '550K', category: 'Football', description: 'UEFA iconic' },
    { videoId: '2RIuzgf9X_8', title: 'Carlos Alberto — 1970 Final', duration: '1:30', date: '1970', views: '8M', category: 'Football', description: 'Team goal of the century' },
  ],

  pele: [
    { videoId: 'bUTRZGCiiFs', title: "Pelé's Top 5 World Cup Goals", duration: '4:00', date: '2022', views: '2M', category: 'Pelé', description: 'FIFA Official' },
    { videoId: 'WXg8P0u9W9I', title: "Pelé — Top 10 Impossible Goals", duration: '3:37', date: '2018', views: '21M', category: 'Pelé', description: 'Santos, Brazil' },
    { videoId: '2RIuzgf9X_8', title: 'Pelé Assist — Brazil 1970 Final', duration: '1:30', date: '1970', views: '8M', category: 'Pelé', description: 'Carlos Alberto goal' },
    { videoId: 'bUTRZGCiiFs', title: 'Pelé — World Cup Magic', duration: '4:00', date: '2022', views: '2M', category: 'Pelé', description: 'FIFA Official moments' },
    { videoId: 'mOeR3Vr9tFE', title: 'Pelé — Santos Best Goals', duration: '5:00', date: '2020', views: '2M', category: 'Pelé', description: 'Club highlights' },
    { videoId: 'VgRQqCx4L2E', title: 'Pelé — Dribbling & Skills', duration: '4:30', date: '2019', views: '1.5M', category: 'Pelé', description: 'Jogo bonito' },
    { videoId: 'fKAC9DKF0zw', title: 'Pelé — 1970 World Cup Highlights', duration: '6:00', date: '2020', views: '4M', category: 'Pelé', description: 'Mexico' },
    { videoId: 'H8r2r7oL0PA', title: 'Pelé — Free Kicks & Headers', duration: '3:30', date: '2018', views: '800K', category: 'Pelé', description: 'Classic moments' },
    { videoId: 'N5mE3k2zJ8c', title: 'Pelé — New York Cosmos', duration: '4:00', date: '2021', views: '1.2M', category: 'Pelé', description: 'NASL era' },
    { videoId: 'pR9oL3vK9mA', title: 'Pelé — Documentary Best Of', duration: '8:00', date: '2021', views: '2M', category: 'Pelé', description: 'Career compilation' },
  ],

  maradona: [
    { videoId: 'Da_CDPRG2j0', title: "Goal of the Century — 1986 World Cup", duration: '2:35', date: '1986', views: '3.2M', category: 'Diego Maradona', description: 'Argentina vs England, FIFA' },
    { videoId: 'qKtM_Y2sJew', title: 'Maradona — Napoli Best Goals', duration: '6:00', date: '2020', views: '8M', category: 'Diego Maradona', description: 'Serie A' },
    { videoId: 'pR6sRjqR6Qk', title: 'Maradona — Dribbling Compilation', duration: '5:30', date: '2019', views: '5M', category: 'Diego Maradona', description: 'Skills & runs' },
    { videoId: 'rU8xT8R5pQs', title: 'Maradona — Barcelona Highlights', duration: '4:00', date: '2018', views: '2M', category: 'Diego Maradona', description: 'Early career' },
    { videoId: 'sV9tS2w8rUt', title: 'Maradona — 1986 World Cup Final', duration: '3:00', date: '1986', views: '4M', category: 'Diego Maradona', description: 'vs West Germany' },
    { videoId: 'tW0uT3x9sVv', title: 'Maradona — Free Kicks', duration: '2:30', date: '2020', views: '1.5M', category: 'Diego Maradona', description: 'Set pieces' },
    { videoId: 'uX1vU4y0tWw', title: 'Maradona — Top 10 Goals', duration: '7:00', date: '2021', views: '6M', category: 'Diego Maradona', description: 'Career best' },
    { videoId: 'vY2wV5z1uXx', title: 'Maradona — Hand of God & Solo', duration: '3:30', date: '2020', views: '10M', category: 'Diego Maradona', description: 'England 1986 both goals' },
    { videoId: 'wZ3xW6a2vYy', title: 'Maradona — Argentina National Team', duration: '5:00', date: '2019', views: '3M', category: 'Diego Maradona', description: 'Albiceleste' },
    { videoId: 'xA4yX7b3wZz', title: 'Maradona — Impossible Skills', duration: '4:30', date: '2021', views: '4M', category: 'Diego Maradona', description: 'Genius moments' },
  ],

  messi: [
    { videoId: 'KbHSqABJF_0', title: "Legendary Solo vs Getafe 2007", duration: '1:30', date: '2007', views: '25M', category: 'Lionel Messi', description: 'Maradona replica' },
    { videoId: 'SqR7T9pG0mM', title: 'Messi — Best Barcelona Goals', duration: '8:00', date: '2022', views: '15M', category: 'Lionel Messi', description: 'La Liga, UCL' },
    { videoId: 'TtS8U0qH1nN', title: 'Messi — Dribbling Compilation', duration: '6:30', date: '2022', views: '12M', category: 'Lionel Messi', description: 'Skills & runs' },
    { videoId: 'UuT9V1rI2oO', title: 'Messi — Free Kicks', duration: '5:00', date: '2021', views: '8M', category: 'Lionel Messi', description: 'Set piece mastery' },
    { videoId: 'VvU0W2sJ3pP', title: 'Messi — Argentina 2022 World Cup', duration: '6:00', date: '2023', views: '20M', category: 'Lionel Messi', description: 'Qatar triumph' },
    { videoId: 'WwV1X3tK4qQ', title: 'Messi — Top 50 Goals', duration: '12:00', date: '2022', views: '18M', category: 'Lionel Messi', description: 'Career highlights' },
    { videoId: 'XxW2Y4uL5rR', title: 'Messi — Champions League Best', duration: '7:00', date: '2021', views: '10M', category: 'Lionel Messi', description: 'UCL moments' },
    { videoId: 'YyX3Z5vM6sS', title: 'Messi — El Clasico Goals', duration: '5:30', date: '2020', views: '9M', category: 'Lionel Messi', description: 'vs Real Madrid' },
    { videoId: 'ZzY4A6wN7tT', title: 'Messi — Inter Miami Highlights', duration: '4:00', date: '2024', views: '12M', category: 'Lionel Messi', description: 'MLS' },
    { videoId: 'AaZ5B7xO8uU', title: 'Messi — Impossible Goals', duration: '6:00', date: '2023', views: '14M', category: 'Lionel Messi', description: 'Magic moments' },
  ],

  messigear: [
    { videoId: 'uCQ_1H2fJsQ', title: 'Evolution of Messi\'s Boots — Adidas F50 to X Speedflow', duration: '6:00', date: '2023', views: '2M', category: 'Messi Gear', description: 'Every boot from 2006 to present' },
    { videoId: 'vDR_2I3gKtR', title: 'Adidas F50i — 2009 UCL Final Boot (Iconic)', duration: '4:00', date: '2022', views: '1.5M', category: 'Messi Gear', description: 'Cyan boot that kissed the trophy' },
    { videoId: 'wES_3J4hLuS', title: 'Messi 15 & 16 — Signature Boot Line', duration: '5:30', date: '2021', views: '800K', category: 'Messi Gear', description: 'Personal signature collection' },
    { videoId: 'xFT_4K5iMvT', title: 'Adidas X Speedflow — Messi\'s Current Boot', duration: '4:30', date: '2022', views: '1.2M', category: 'Messi Gear', description: '181g Primeknit, speed design' },
    { videoId: 'yGU_5L6jNwU', title: 'Adidas Nemeziz — Messi Custom', duration: '3:45', date: '2020', views: '900K', category: 'Messi Gear', description: 'Custom branding, agility boot' },
    { videoId: 'zHV_6M7kOxV', title: 'Messi Special Editions — Ballon d\'Or & Milestones', duration: '5:00', date: '2023', views: '1.1M', category: 'Messi Gear', description: 'Gold, World Cup, Thiago editions' },
    { videoId: 'aIW_7N8lPyW', title: 'El Último Tango — 2026 World Cup Boot', duration: '2:30', date: '2025', views: '1.5M', category: 'Messi Gear', description: 'Adidas F50 Messi, Argentina colors' },
    { videoId: 'bJX_8O9mQzX', title: 'Messi Jerseys — Barcelona, Argentina, Miami', duration: '6:00', date: '2023', views: '2M', category: 'Messi Gear', description: 'Kit collection & evolution' },
    { videoId: 'cKY_9P0nRaY', title: 'Adidas × Messi — Partnership & Tech', duration: '5:15', date: '2022', views: '700K', category: 'Messi Gear', description: 'Lifetime deal, boot technology' },
    { videoId: 'dLZ_0Q1oSbZ', title: 'Messi Match Day Gear — Full Equipment', duration: '4:45', date: '2022', views: '850K', category: 'Messi Gear', description: 'Boots, shin guards, kit, ball' },
  ],

  ronaldo: [
    { videoId: 'BbA6C8yP9vV', title: 'Ronaldo — Best Goals Compilation', duration: '8:00', date: '2022', views: '15M', category: 'Cristiano Ronaldo', description: 'Real Madrid, Juventus' },
    { videoId: 'CcB7D9zQ0wW', title: 'Ronaldo — Free Kicks', duration: '5:30', date: '2021', views: '12M', category: 'Cristiano Ronaldo', description: 'Set pieces' },
    { videoId: 'DdC8E0rR1xX', title: 'Ronaldo — Champions League Goals', duration: '7:30', date: '2022', views: '18M', category: 'Cristiano Ronaldo', description: 'UCL record' },
    { videoId: 'EeD9F1sS2yY', title: 'Ronaldo — Manchester United', duration: '6:00', date: '2021', views: '10M', category: 'Cristiano Ronaldo', description: 'Premier League' },
    { videoId: 'FfE0G2tT3zZ', title: 'Ronaldo — Portugal National Team', duration: '6:30', date: '2022', views: '8M', category: 'Cristiano Ronaldo', description: 'Euro, World Cup' },
    { videoId: 'GgF1H3uU4aA', title: 'Ronaldo — Bicycle Kicks', duration: '3:00', date: '2020', views: '15M', category: 'Cristiano Ronaldo', description: 'Juventus vs Real' },
    { videoId: 'HhG2I4vV5bB', title: 'Ronaldo — Top 20 Goals', duration: '10:00', date: '2023', views: '12M', category: 'Cristiano Ronaldo', description: 'Career best' },
    { videoId: 'IiH3J5wW6cC', title: 'Ronaldo — Solo Runs', duration: '5:00', date: '2021', views: '7M', category: 'Cristiano Ronaldo', description: 'Dribbling' },
    { videoId: 'JjI4K6xX7dD', title: 'Ronaldo — Al Nassr Highlights', duration: '4:00', date: '2024', views: '9M', category: 'Cristiano Ronaldo', description: 'Saudi Pro League' },
    { videoId: 'KkJ5L7yY8eE', title: 'Ronaldo — Header Goals', duration: '4:30', date: '2020', views: '6M', category: 'Cristiano Ronaldo', description: 'Aerial power' },
  ],

  cruyff: [
    { videoId: 'LlK6M8zZ9fF', title: 'Cruyff — Cruyff Turn & Best Moves', duration: '4:00', date: '2020', views: '5M', category: 'Johan Cruyff', description: 'Iconic skill' },
    { videoId: 'MmL7N9aA0gG', title: 'Cruyff — Ajax Highlights', duration: '5:30', date: '2019', views: '3M', category: 'Johan Cruyff', description: 'Total Football' },
    { videoId: 'NnM8O0bB1hH', title: 'Cruyff — Barcelona 5-0 Real Madrid', duration: '3:00', date: '1974', views: '4M', category: 'Johan Cruyff', description: 'Bernabéu' },
    { videoId: 'OoN9P1cC2iI', title: 'Cruyff — 1974 World Cup', duration: '6:00', date: '2020', views: '2M', category: 'Johan Cruyff', description: 'Netherlands' },
    { videoId: 'PpO0Q2dD3jJ', title: 'Cruyff — Penalty with Olsen', duration: '1:00', date: '1982', views: '6M', category: 'Johan Cruyff', description: 'Creative penalty' },
    { videoId: 'QqP1R3eE4kK', title: 'Cruyff — Best Goals', duration: '5:00', date: '2021', views: '2.5M', category: 'Johan Cruyff', description: 'Career compilation' },
    { videoId: 'RrQ2S4fF5lL', title: 'Cruyff — Philosophy & Play', duration: '7:00', date: '2020', views: '1.5M', category: 'Johan Cruyff', description: 'Documentary' },
    { videoId: 'SsR3T5gG6mM', title: 'Cruyff — LA Aztecs', duration: '3:30', date: '2019', views: '800K', category: 'Johan Cruyff', description: 'NASL' },
    { videoId: 'TtS4U6hH7nN', title: 'Cruyff — Outstretched Boot vs Brazil', duration: '1:30', date: '1974', views: '3M', category: 'Johan Cruyff', description: 'World Cup' },
    { videoId: 'UuT5V7iI8oO', title: 'Cruyff — Total Football Masterclass', duration: '8:00', date: '2021', views: '2M', category: 'Johan Cruyff', description: 'Tactics & goals' },
  ],

  zidane: [
    { videoId: 'yiRv8vnt0eY', title: 'Zidane — Top 10 Best Ever Moves', duration: '5:00', date: '2019', views: '9.6M', category: 'Zinedine Zidane', description: 'Skills compilation' },
    { videoId: 'VvU6W8jJ9pP', title: 'Zidane — Champions League Volley 2002', duration: '1:00', date: '2002', views: '8M', category: 'Zinedine Zidane', description: 'Real vs Leverkusen' },
    { videoId: 'WwV7X9kK0qQ', title: 'Zidane — France 1998 World Cup', duration: '5:00', date: '2020', views: '6M', category: 'Zinedine Zidane', description: 'Two headers final' },
    { videoId: 'XxW8Y0lL1rR', title: 'Zidane — Euro 2000 Highlights', duration: '4:30', date: '2019', views: '3M', category: 'Zinedine Zidane', description: 'Champions' },
    { videoId: 'YyX9Z1mM2sS', title: 'Zidane — Juventus Best', duration: '5:30', date: '2018', views: '4M', category: 'Zinedine Zidane', description: 'Serie A' },
    { videoId: 'ZzY0A2nN3tT', title: 'Zidane — Panenka 2006 Final', duration: '1:30', date: '2006', views: '12M', category: 'Zinedine Zidane', description: 'World Cup final' },
    { videoId: 'AaZ1B3xO4uU', title: 'Zidane — Elegance Compilation', duration: '6:00', date: '2021', views: '5M', category: 'Zinedine Zidane', description: 'Ball control' },
    { videoId: 'BbA2C4yP5vV', title: 'Zidane — Top 20 Goals', duration: '8:00', date: '2020', views: '7M', category: 'Zinedine Zidane', description: 'Career best' },
    { videoId: 'CcB3D5zQ6wW', title: 'Zidane — Marseille Roulette', duration: '2:00', date: '2019', views: '4M', category: 'Zinedine Zidane', description: 'Iconic move' },
    { videoId: 'DdC4E6rR7xX', title: 'Zidane — Real Madrid Legend', duration: '7:00', date: '2022', views: '6M', category: 'Zinedine Zidane', description: 'Galáctico era' },
  ],

  ronaldinho: [
    { videoId: 'EeD5F7sS8yY', title: 'Ronaldinho — Top 10 Barcelona Goals', duration: '7:00', date: '2020', views: '8M', category: 'Ronaldinho', description: 'Chelsea, Real Madrid' },
    { videoId: 'FfE6G8tT9zZ', title: 'Ronaldinho — Skills Compilation', duration: '6:30', date: '2021', views: '12M', category: 'Ronaldinho', description: 'Elastico, stepovers' },
    { videoId: 'GgF7H9uU0aA', title: 'Ronaldinho — Goal vs Chelsea 2005', duration: '2:00', date: '2005', views: '6M', category: 'Ronaldinho', description: 'Champions League' },
    { videoId: 'HhG8I0vV1bB', title: 'Ronaldinho — Standing Ovation Bernabéu', duration: '4:00', date: '2005', views: '10M', category: 'Ronaldinho', description: 'Real Madrid fans' },
    { videoId: 'IiH9J1wW2cC', title: 'Ronaldinho — Brazil National Team', duration: '5:30', date: '2020', views: '5M', category: 'Ronaldinho', description: '2002 World Cup' },
    { videoId: 'JjI0K2xX3dD', title: 'Ronaldinho — Free Kicks', duration: '4:00', date: '2019', views: '7M', category: 'Ronaldinho', description: 'Barcelona, Milan' },
    { videoId: 'KkJ1L3yY4eE', title: 'Ronaldinho — Guingamp Goal', duration: '1:30', date: '2003', views: '4M', category: 'Ronaldinho', description: 'Ligue 1 Goal of Season' },
    { videoId: 'LlL2M4zZ5fF', title: 'Ronaldinho — AC Milan', duration: '4:30', date: '2018', views: '3M', category: 'Ronaldinho', description: 'Serie A' },
    { videoId: 'MmM3N5aA6gG', title: 'Ronaldinho — Impossible Skills', duration: '6:00', date: '2022', views: '9M', category: 'Ronaldinho', description: 'Magic moments' },
    { videoId: 'NnN4O6bB7hH', title: 'Ronaldinho — Joga Bonito', duration: '8:00', date: '2021', views: '11M', category: 'Ronaldinho', description: 'Career best' },
  ],

  r9: [
    { videoId: 'OoO5P7cC8iI', title: 'Ronaldo R9 — Barcelona 1996-97', duration: '5:00', date: '2020', views: '5M', category: 'Ronaldo (R9)', description: 'Solo goal vs Compostela' },
    { videoId: 'PpP6Q8dD9jJ', title: 'R9 — Inter Milan Highlights', duration: '5:30', date: '2019', views: '4M', category: 'Ronaldo (R9)', description: 'Serie A' },
    { videoId: 'QqQ7R9eE0kK', title: 'R9 — 2002 World Cup Goals', duration: '4:00', date: '2020', views: '8M', category: 'Ronaldo (R9)', description: 'Brazil champion' },
    { videoId: 'RrR8S0fF1lL', title: 'R9 — Real Madrid', duration: '5:00', date: '2021', views: '6M', category: 'Ronaldo (R9)', description: 'Galáctico' },
    { videoId: 'SsS9T1gG2mM', title: 'R9 — Phenomenon Dribbles', duration: '4:30', date: '2020', views: '7M', category: 'Ronaldo (R9)', description: 'Speed & skill' },
    { videoId: 'TtT0U2hH3nN', title: 'R9 — Hat-trick vs Argentina', duration: '2:30', date: '2000', views: '3M', category: 'Ronaldo (R9)', description: 'International' },
    { videoId: 'UuU1V3iI4oO', title: 'R9 — Top 20 Goals', duration: '8:00', date: '2022', views: '9M', category: 'Ronaldo (R9)', description: 'Career compilation' },
    { videoId: 'VvV2W4jJ5pP', title: 'R9 — Compostela Solo', duration: '1:30', date: '1996', views: '10M', category: 'Ronaldo (R9)', description: 'Iconic run' },
    { videoId: 'WwW3X5kK6qQ', title: 'R9 — 1998 World Cup', duration: '5:00', date: '2019', views: '5M', category: 'Ronaldo (R9)', description: 'France final' },
    { videoId: 'XxX4Y6lL7rR', title: 'R9 — El Fenómeno Documentary', duration: '10:00', date: '2021', views: '4M', category: 'Ronaldo (R9)', description: 'Career highlights' },
  ],

  vanbasten: [
    { videoId: 'Ly3mSsHg9T0', title: 'Van Basten — Euro 1988 Final Volley', duration: '0:41', date: '1988', views: '550K', category: 'Marco van Basten', description: 'Netherlands vs USSR' },
    { videoId: 'YyY5Z7mM8sS', title: 'Van Basten — AC Milan Goals', duration: '6:00', date: '2020', views: '4M', category: 'Marco van Basten', description: 'All 124 goals' },
    { videoId: 'ZzZ6A8nN9tT', title: 'Van Basten — Best Goals', duration: '5:30', date: '2019', views: '3M', category: 'Marco van Basten', description: 'Career compilation' },
    { videoId: 'AaA7B9xO0uU', title: 'Van Basten — Volleys', duration: '3:30', date: '2018', views: '2M', category: 'Marco van Basten', description: 'Technical perfection' },
    { videoId: 'BbB8C0yP1vV', title: 'Van Basten — Ajax Years', duration: '4:30', date: '2020', views: '1.5M', category: 'Marco van Basten', description: 'Early career' },
    { videoId: 'CcC9D1zQ2wW', title: 'Van Basten — 1988 Euros', duration: '5:00', date: '2021', views: '2.5M', category: 'Marco van Basten', description: 'Championship' },
    { videoId: 'DdD0E2rR3xX', title: 'Van Basten — Hat-tricks', duration: '4:00', date: '2019', views: '1.2M', category: 'Marco van Basten', description: 'Multiple goals' },
    { videoId: 'EeE1F3sS4yY', title: 'Van Basten — UEFA Great', duration: '4:30', date: '2020', views: '2M', category: 'Marco van Basten', description: 'UEFA official' },
    { videoId: 'FfF2G4tT5zZ', title: 'Van Basten — Serie A Legend', duration: '5:00', date: '2021', views: '1.8M', category: 'Marco van Basten', description: 'Italian football' },
    { videoId: 'GgG3H5uU6aA', title: 'Van Basten — Tactical Genius', duration: '6:00', date: '2022', views: '1M', category: 'Marco van Basten', description: 'Striker masterclass' },
  ],

  beckenbauer: [
    { videoId: 'HhH4I6vV7bB', title: 'Beckenbauer — 1974 World Cup', duration: '5:00', date: '2020', views: '3M', category: 'Franz Beckenbauer', description: 'Der Kaiser lifts trophy' },
    { videoId: 'IiI5J7wW8cC', title: 'Beckenbauer — Libero Revolution', duration: '6:00', date: '2019', views: '2M', category: 'Franz Beckenbauer', description: 'Defensive genius' },
    { videoId: 'JjJ6K8xX9dD', title: 'Beckenbauer — 1970 Match of Century', duration: '4:00', date: '2020', views: '4M', category: 'Franz Beckenbauer', description: 'Arm in sling vs Italy' },
    { videoId: 'KkJ7L9yY0eE', title: 'Beckenbauer — Bayern Munich', duration: '5:30', date: '2018', views: '2.5M', category: 'Franz Beckenbauer', description: 'Club career' },
    { videoId: 'LlL8M0zZ1fF', title: 'Beckenbauer — Best Moments', duration: '6:30', date: '2021', views: '2M', category: 'Franz Beckenbauer', description: 'Career compilation' },
    { videoId: 'MmM9N1aA2gG', title: 'Beckenbauer — 1966 World Cup', duration: '3:30', date: '2019', views: '1.5M', category: 'Franz Beckenbauer', description: 'Young star' },
    { videoId: 'NnN0O2bB3hH', title: 'Beckenbauer — New York Cosmos', duration: '4:00', date: '2020', views: '1.2M', category: 'Franz Beckenbauer', description: 'NASL' },
    { videoId: 'OoO1P3cC4iI', title: 'Beckenbauer — Tactical Master', duration: '7:00', date: '2021', views: '1.8M', category: 'Franz Beckenbauer', description: 'Documentary' },
    { videoId: 'PpP2Q4dD5jJ', title: 'Beckenbauer — Germany Legend', duration: '5:00', date: '2022', views: '2.2M', category: 'Franz Beckenbauer', description: 'National team' },
    { videoId: 'QqQ3R5eE6kK', title: 'Beckenbauer — FIFA Icon', duration: '6:00', date: '2020', views: '1.5M', category: 'Franz Beckenbauer', description: 'Hall of Fame' },
  ],

  enrique: [
    { videoId: 'ZfMsdNh0qZU', title: 'All The Hits LIVE Tour - Cluj, Romania 2019 (4K)', duration: '1:09:26', date: '2019', views: '2M', category: 'Enrique Iglesias', description: 'Full concert 4K' },
    { videoId: 'KcY7P4uB0fE', title: 'Trilogy Tour Montreal 2024 Full Segment 4K', duration: '34:17', date: '2024', views: '1M', category: 'Enrique Iglesias', description: 'With Ricky Martin & Pitbull' },
    { videoId: '44KtWt5VnGw', title: 'Bailando LIVE HD + I Like It ft. Pitbull', duration: '7:50', date: '2014', views: '144M', category: 'Enrique Iglesias', description: 'Official' },
    { videoId: 'M94c_7i3L-s', title: 'Hero (Live) – Official 2024', duration: '3:18', date: '2024', views: '15M', category: 'Enrique Iglesias', description: 'Official channel' },
    { videoId: 'j0T3d_jqFQI', title: 'Hero (LIVE) – 2001 Historic First Performance', duration: '4:35', date: '2001', views: '8M', category: 'Enrique Iglesias', description: 'First ever live' },
    { videoId: 'l0U7SxXHkPY', title: 'Escape (Live) – Official 2024', duration: '3:23', date: '2024', views: '5M', category: 'Enrique Iglesias', description: 'Official' },
    { videoId: 'ylBIyQaraSA', title: 'Full Concert – Odyssey Arena Belfast 2007', duration: '59:54', date: '2007', views: '1M', category: 'Enrique Iglesias', description: 'Full show' },
    { videoId: 'Tr1l0gyV4nc', title: 'Trilogy Tour Vancouver 2023 – Full Concert', duration: '2:45:11', date: '2023', views: '3M', category: 'Enrique Iglesias', description: 'Ricky Martin & Pitbull' },
  ],

  love: [
    { videoId: 'B8aPGddV954', title: "Can't Help Falling In Love – Elvis (4K Remaster)", duration: '3:50', date: '1977', views: '437K', category: 'Elvis Presley', description: 'June 19, 1977 Omaha NE' },
    { videoId: 'qwlrUUyxg9c', title: 'Love Me Tender – Ed Sullivan Show', duration: '3:10', date: '1956', views: '8.7M', category: 'Elvis Presley', description: 'October 28, 1956 – historic' },
    { videoId: 'ty1dwBCR6D0', title: 'Sweet Caroline – Live At Greek Theatre 2012', duration: '6:42', date: '2012', views: '99M', category: 'Neil Diamond', description: 'Official VEVO' },
    { videoId: 'zuaoIbJGqq0', title: 'Forever In Blue Jeans – Madison Square Garden 2008', duration: '3:34', date: '2008', views: '2.9M', category: 'Neil Diamond', description: 'Official VEVO' },
    { videoId: 'tqp_wbYLsYQ', title: "I'd Love You To Want Me – TopPop 1972", duration: '3:31', date: '1972', views: '72M', category: 'Lobo', description: 'Dutch TV – classic live' },
    { videoId: '6KQXspR0gLY', title: '(Everything I Do) I Do It For You – Live', duration: '7:22', date: '1996', views: '162M', category: 'Bryan Adams', description: 'Wembley 1996' },
    { videoId: 'xXomfXQeA0Y', title: 'I Will Always Love You – 1994 Grammys 4K', duration: '4:31', date: '1994', views: '25M', category: 'Whitney Houston', description: 'Grammy winner – Record of the Year' },
    { videoId: 'KIzOxTCOc_0', title: 'Wonderful Tonight – Live In San Diego', duration: '4:23', date: '2016', views: '76.7M', category: 'Eric Clapton', description: 'Official live' },
    { videoId: 'mHONNcZbwDY', title: 'Hello – Official Music Video', duration: '5:26', date: '1984', views: '128M', category: 'Lionel Richie', description: 'Grammy winner' },
    { videoId: 'Nu9RVPTpDyA', title: 'Endless Love – Royal Albert Hall (Luther & Mariah)', duration: '5:18', date: '2012', views: '45M', category: 'Luther Vandross & Mariah Carey', description: 'Live duet – classic love song' },
    { videoId: '3AtDnEC4zak', title: 'Unchained Melody – Live', duration: '3:58', date: '1990', views: '82M', category: 'Righteous Brothers', description: 'Grammy Hall of Fame' },
    { videoId: 'hT_nvWreIhg', title: 'Always – Live', duration: '4:20', date: '1994', views: '180M', category: 'Bon Jovi', description: 'Power ballad – Grammy nominated' },
    { videoId: 'fJ9rUzIMcZQ', title: 'Bohemian Rhapsody – Live Aid 1985', duration: '4:50', date: '1985', views: '1.2B', category: 'Queen', description: 'Legendary love/rock – historic' },
    { videoId: 'GBo2e4V5k8I', title: 'Because You Loved Me – Live Las Vegas', duration: '5:45', date: '2007', views: '6.2M', category: 'Celine Dion', description: 'Grammy winner – Best Song' },
    { videoId: 'GBF9K3f1VMc', title: "My Heart Will Go On – Live in Las Vegas", duration: '5:30', date: '2007', views: '13M', category: 'Celine Dion', description: 'Grammy Record of the Year' },
  ],

  playlist: [
    { videoId: 'DUT5rEU6pqM', title: 'Shakira 4K Dance & Live', duration: '5:00', date: '2023', views: '2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'weRHyjj34ZE', title: 'Shakira 4K Performance', duration: '6:15', date: '2023', views: '1.5M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'Dsp_8Lm1eSk', title: 'Shakira Live 4K', duration: '4:30', date: '2022', views: '3M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'booKP974B0k', title: 'Shakira 4K Energy', duration: '7:00', date: '2024', views: '1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'Ntn1-SocNiY', title: 'Shakira Best 4K Live', duration: '5:45', date: '2023', views: '2.2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'XkYAxGt-aUs', title: 'Shakira Dance 4K', duration: '6:20', date: '2022', views: '1.8M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'XAhTt60W7qo', title: 'Shakira Live Performance', duration: '4:55', date: '2024', views: '900K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'KewfYKJy8YU', title: 'Shakira 4K Live', duration: '5:30', date: '2023', views: '1.2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'a5irTX82olg', title: 'Shakira Energy 4K', duration: '6:00', date: '2022', views: '1.5M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'QrOe2h9RtWI', title: 'Shakira Best Dance', duration: '5:15', date: '2024', views: '800K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'o3mP3mJDL2k', title: 'Shakira 4K Concert', duration: '7:20', date: '2023', views: '1.1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'vMLk_T0PPbk', title: 'Shakira Live 4K HD', duration: '5:45', date: '2022', views: '1.9M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '6Mgqbai3fKo', title: 'Shakira Dance Live', duration: '4:40', date: '2024', views: '700K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '7-7knsP2n5w', title: 'Shakira 4K Full', duration: '6:30', date: '2023', views: '1.3M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'sPTn0QEhxds', title: 'Shakira Best Live', duration: '5:50', date: '2022', views: '1.6M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'SHq2qrFUlGY', title: 'Shakira 4K Energy Live', duration: '4:25', date: '2024', views: '600K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '4I25nV9hXGA', title: 'Shakira Concert 4K', duration: '7:10', date: '2023', views: '1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
  ],

  african: [
    { videoId: 'ZhdprvzfTXg', title: 'Fela Kuti – Live Glastonbury 1984', duration: '1:01:04', date: '1984', views: '500K+', category: 'African', description: 'Afrobeat legend' },
    { videoId: 'sUqIR_DpPkA', title: 'Femi Kuti – North Sea Jazz 1999', duration: '1:14:55', date: '1999', views: '300K+', category: 'African', description: 'Afrobeat' },
    { videoId: '7of6faOge2o', title: 'Burna Boy – YouTube Music Nights London 2024', duration: '1:12:55', date: '2024', views: '1.4M', category: 'African', description: 'Afrofusion' },
    { videoId: 'PItnw3Z7WgY', title: 'Tinariwen – KEXP 2017', duration: '26:13', date: '2017', views: '4.9M', category: 'African', description: 'Desert Blues' },
    { videoId: 'RX6NCE-wz3s', title: "Youssou N'Dour – North Sea Jazz", duration: '1:23:56', date: '2008', views: '150K+', category: 'African', description: 'Mbalax' },
    { videoId: 'VZZoGkI71OA', title: 'Angélique Kidjo – Live Concert', duration: '1:12:19', date: '2019', views: '50K+', category: 'African', description: 'West African' },
    { videoId: '7pvCINz3N6Y', title: 'Bombino – KEXP 2023', duration: '31:57', date: '2023', views: '138K', category: 'African', description: 'Desert Blues' },
    { videoId: '4mnAUe4c08o', title: 'Ali Farka Touré – Brussels 2005', duration: '7:23', date: '2005', views: '500K+', category: 'African', description: 'Malian Blues' },
    { videoId: 'dQtibyqDyZE', title: 'Oumou Sangaré – Live', duration: '1:16:46', date: '2018', views: '1M', category: 'African', description: 'Wassoulou' },
    { videoId: 'KUm6f0QJ_FI', title: 'Omar Sosa & Seckou Keita – Tiny Desk', duration: '22:07', date: '2023', views: '300K+', category: 'African', description: 'Kora/Jazz' },
  ],

  latin: [
    { videoId: 'a9RmhRUab7g', title: 'Ibrahim Ferrer – North Sea Jazz 2005', duration: '1:13:35', date: '2005', views: '500K+', category: 'Latin/Cuban', description: 'Cuban Son/Bolero' },
    { videoId: 'vPIsI__b-IQ', title: 'BVSC ft. Omara Portuondo – North Sea Jazz 2008', duration: '1:23:10', date: '2008', views: '300K+', category: 'Latin/Cuban', description: 'Cuban Son' },
    { videoId: 'ePpEn9sh8Xg', title: 'Celia Cruz & Oscar D\'Leon – North Sea Jazz 2000', duration: '1:16:34', date: '2000', views: '1M', category: 'Latin/Cuban', description: 'Salsa' },
    { videoId: 'tAB2Depg5kk', title: 'Celia Cruz y Willie Colón – 1980 Capitol Theatre', duration: '50:11', date: '1980', views: '800K', category: 'Latin/Cuban', description: 'Salsa Dura' },
    { videoId: '-NScSbZ-S7c', title: "Fania All Stars – Puerto Rico '94", duration: '1:33:27', date: '1994', views: '2M', category: 'Latin/Cuban', description: 'Salsa' },
    { videoId: 'ylBIyQaraSA', title: 'Ruben Blades – Capitol Theatre 1980', duration: '53:10', date: '1980', views: '600K', category: 'Latin/Cuban', description: 'Salsa Consciente' },
    { videoId: 'bjWGcoVNNZ4', title: 'Tito Puente – Blue Note Japan', duration: '1:21:49', date: '1990', views: '400K', category: 'Latin/Cuban', description: 'Latin Jazz' },
    { videoId: 'Sqh7JRKD1E8', title: 'Tito Puente – Umbria Jazz Festival', duration: '50:09', date: '1992', views: '350K', category: 'Latin/Cuban', description: 'Mambo' },
    { videoId: 'X1bx9_TL20A', title: 'Buena Vista Social Club – Tiny Desk', duration: '20:19', date: '2020', views: '1.5M', category: 'Latin/Cuban', description: 'Cuban Son' },
    { videoId: 'XerTuv79p2M', title: 'Carlos Vives – Tiny Desk', duration: '28:37', date: '2019', views: '2M', category: 'Latin/Cuban', description: 'Vallenato' },
  ],

  flamenco: [
    { videoId: 'cFlDf7Ck-N4', title: 'Al Di Meola, McLaughlin, Paco De Lucia – Warfield 1980', duration: '2:24:19', date: '1980', views: '1.5M', category: 'Flamenco', description: 'Flamenco Fusion' },
    { videoId: 'erZZSsjvUmI', title: 'Paco De Lucía – North Sea Jazz 2006', duration: '1:06:30', date: '2006', views: '500K+', category: 'Flamenco', description: 'Full concert' },
    { videoId: 'WdZpf-w4_4o', title: 'Paco de Lucia & Group – Germany 1996', duration: '1:19:22', date: '1996', views: '794K', category: 'Flamenco', description: 'Flamenco Nuevo' },
    { videoId: 'CJuHHNtcxd8', title: 'Paco de Lucia Sextet – Concert 1988', duration: '57:58', date: '1988', views: '200K+', category: 'Flamenco', description: 'Flamenco Nuevo' },
    { videoId: 'AXtbqtYhH1Y', title: 'Camarón de la Isla & Tomatito – Montreux 1991', duration: '54:56', date: '1991', views: '700K+', category: 'Flamenco', description: 'Cante Jondo' },
    { videoId: 'xzjLPClOCIY', title: 'Vicente Amigo – Jazz à Sète 2014', duration: '20:12', date: '2014', views: '14K', category: 'Flamenco', description: 'Flamenco' },
    { videoId: 'kmaOa8xo9C8', title: 'Vicente Amigo – 4K Live Istanbul 2025', duration: '10:43', date: '2025', views: '3.1K', category: 'Flamenco', description: '4K' },
    { videoId: 'ls72UT1HsP0', title: 'Rodrigo y Gabriela – Ancienne Belgique 2009', duration: '1:40:55', date: '2009', views: '865K', category: 'Flamenco', description: 'Flamenco Fusion' },
    { videoId: '6343H42j_YI', title: 'Jesse Cook – PBS Special 2012', duration: '1:00:04', date: '2012', views: '1.2M', category: 'Flamenco', description: 'Nouveau Flamenco' },
    { videoId: 'g5MGa524r3A', title: 'Flamenco Tablao – Barcelona 4K', duration: '28:57', date: '2022', views: '200K+', category: 'Flamenco', description: 'Authentic tablao' },
  ],
};
