/* eslint-disable no-unused-vars */
const CONCERT_DATA = {
  playlistUrl: 'https://youtube.com/playlist?list=PLl1nGeQ1UIbw0lAfx8bVlPcF61i_jV5Ec',

  celine: [
    { videoId: 'vGjnM-nShNs', title: 'Hits Medley (Taking Chances World Tour)', duration: '10:04', date: '2008', views: '142M', category: 'Celine Dion', description: 'Official VEVO — Taking Chances World Tour' },
    { videoId: 'DNyKDI-inps', title: 'My Heart Will Go On (Taking Chances)', duration: '5:10', date: '2008', views: '120M', category: 'Celine Dion', description: 'Official VEVO — Las Vegas' },
    { videoId: 'a1Y73sPHKxw', title: 'The Power of Love (Taking Chances)', duration: '3:32', date: '2008', views: '75M', category: 'Celine Dion', description: 'Official VEVO' },
    { videoId: 'p4W_Mlk1EO4', title: 'All By Myself (Taking Chances)', duration: '5:26', date: '2008', views: '57M', category: 'Celine Dion', description: 'Official VEVO' },
    { videoId: 'X2nUfu3iXkQ', title: "My Heart Will Go On – Billboard Music Awards 2017", duration: '5:11', date: '2017', views: '17M', category: 'Celine Dion', description: 'Official VEVO' },
    { videoId: 'wG2s0fTacP0', title: "It's All Coming Back To Me Now – Live in Las Vegas", duration: '7:11', date: '2007', views: '13M', category: 'Celine Dion', description: 'Official VEVO — A New Day' },
    { videoId: '5c_BQnTQ6rM', title: "The Power of Love & I'm Alive – Elie Saab Riyadh 2024", duration: '14:31', date: '2024', views: '5M', category: 'Celine Dion', description: '4K comeback performance' },
    { videoId: 'GBo2e4V5k8I', title: 'Because You Loved Me – Official Live HD', duration: '5:45', date: '2007', views: '6.2M', category: 'Celine Dion', description: 'Official live' },
    { videoId: 'vKGMxEMjvR8', title: 'Live in Manila 2018 – Full Concert', duration: '1:58:08', date: '2018', views: '2.7M', category: 'Celine Dion', description: 'Full concert HD' },
    { videoId: 'f5N-Eio1iZE', title: 'A New Day – Live in Las Vegas 2007 Full Concert', duration: '1:33:07', date: '2007', views: '2.2M', category: 'Celine Dion', description: 'Full concert' },
  ],

  shakira: [
    { videoId: 'pILCn6VO_RU', title: 'Super Bowl LIV Full Halftime Show', duration: '14:21', date: '2020', views: '300M+', category: 'Shakira', description: 'NFL Official' },
    { videoId: 'BQcgrdkoGbc', title: 'Super Bowl LIV Shakira Only | 4K', duration: '6:14', date: '2020', views: '5M', category: 'Shakira', description: '4K cut' },
    { videoId: 'P1jGg5nMoyc', title: 'Copa América 2024 Finals Performance', duration: '8:09', date: '2024', views: '25M', category: 'Shakira', description: 'Live finals' },
    { videoId: 'uVTifWo9uH0', title: 'MTV VMAs 2023 Video Vanguard', duration: '10:17', date: '2023', views: '25M', category: 'Shakira', description: 'Award performance' },
    { videoId: 'CT8xMunS608', title: 'La La La / Waka Waka – El Dorado Tour', duration: '7:21', date: '2018', views: '102M', category: 'Shakira', description: 'World Tour' },
    { videoId: 'uyAREe7CQDc', title: 'El Dorado World Tour | Full Concert', duration: '2:02:07', date: '2018', views: '2M', category: 'Shakira', description: 'Full 4K' },
    { videoId: 'onlZQ0jKUZc', title: 'Antología (El Dorado World Tour - Live)', duration: '4:01', date: '2018', views: '28M', category: 'Shakira', description: 'Live' },
    { videoId: 'IHqUiOvjlC0', title: 'Live From Paris | Full Concert', duration: '1:39:55', date: '2011', views: '3M', category: 'Shakira', description: 'Full concert' },
    { videoId: 'OZUzX4kbtDU', title: 'Hips Don\'t Lie (Live) ft. Wyclef – Official', duration: '7:11', date: '2006', views: '98M', category: 'Shakira', description: 'Official' },
    { videoId: '2Ndra-1Pwug', title: 'Hips Don\'t Lie – LMYNL Tour w/ Wyclef', duration: '4:55', date: '2024', views: '69M', category: 'Shakira', description: 'World Tour' },
  ],

  enrique: [
    { videoId: 'ZfMsdNh0qZU', title: 'All The Hits LIVE Tour - Cluj, Romania 2019 (4K)', duration: '1:09:26', date: '2019', views: '2M', category: 'Enrique Iglesias', description: 'Full concert 4K' },
    { videoId: 'KcY7P4uB0fE', title: 'Trilogy Tour Montreal 2024 Full Segment 4K', duration: '34:17', date: '2024', views: '1M', category: 'Enrique Iglesias', description: 'With Ricky Martin & Pitbull' },
    { videoId: '44KtWt5VnGw', title: 'Bailando LIVE HD + I Like It ft. Pitbull', duration: '7:50', date: '2014', views: '144M', category: 'Enrique Iglesias', description: 'Official' },
    { videoId: 'M94c_7i3L-s', title: 'Hero (Live) – Official 2024', duration: '3:18', date: '2024', views: '15M', category: 'Enrique Iglesias', description: 'Official channel' },
    { videoId: 'j0T3d_jqFQI', title: 'Hero (LIVE) – 2001 Historic First Performance', duration: '4:35', date: '2001', views: '8M', category: 'Enrique Iglesias', description: 'First ever live' },
    { videoId: 'l0U7SxXHkPY', title: 'Escape (Live) – Official 2024', duration: '3:23', date: '2024', views: '5M', category: 'Enrique Iglesias', description: 'Official' },
    { videoId: 'ylBIyQaraSA', title: 'Full Concert – Odyssey Arena Belfast 2007', duration: '59:54', date: '2007', views: '1M', category: 'Enrique Iglesias', description: 'Full show' },
    { videoId: 'Tr1l0gyV4nc', title: 'Trilogy Tour Vancouver 2023 – Full Concert', duration: '2:45:11', date: '2023', views: '3M', category: 'Enrique Iglesias', description: 'Ricky Martin & Pitbull' },
  ],

  love: [
    { videoId: 'B8aPGddV954', title: "Can't Help Falling In Love – Elvis (4K Remaster)", duration: '3:50', date: '1977', views: '437K', category: 'Elvis Presley', description: 'June 19, 1977 Omaha NE' },
    { videoId: 'qwlrUUyxg9c', title: 'Love Me Tender – Ed Sullivan Show', duration: '3:10', date: '1956', views: '8.7M', category: 'Elvis Presley', description: 'October 28, 1956 – historic' },
    { videoId: 'ty1dwBCR6D0', title: 'Sweet Caroline – Live At Greek Theatre 2012', duration: '6:42', date: '2012', views: '99M', category: 'Neil Diamond', description: 'Official VEVO' },
    { videoId: 'zuaoIbJGqq0', title: 'Forever In Blue Jeans – Madison Square Garden 2008', duration: '3:34', date: '2008', views: '2.9M', category: 'Neil Diamond', description: 'Official VEVO' },
    { videoId: 'tqp_wbYLsYQ', title: "I'd Love You To Want Me – TopPop 1972", duration: '3:31', date: '1972', views: '72M', category: 'Lobo', description: 'Dutch TV – classic live' },
    { videoId: '6KQXspR0gLY', title: '(Everything I Do) I Do It For You – Live', duration: '7:22', date: '1996', views: '162M', category: 'Bryan Adams', description: 'Wembley 1996' },
    { videoId: 'xXomfXQeA0Y', title: 'I Will Always Love You – 1994 Grammys 4K', duration: '4:31', date: '1994', views: '25M', category: 'Whitney Houston', description: 'Grammy winner – Record of the Year' },
    { videoId: 'KIzOxTCOc_0', title: 'Wonderful Tonight – Live In San Diego', duration: '4:23', date: '2016', views: '76.7M', category: 'Eric Clapton', description: 'Official live' },
    { videoId: 'mHONNcZbwDY', title: 'Hello – Official Music Video', duration: '5:26', date: '1984', views: '128M', category: 'Lionel Richie', description: 'Grammy winner' },
    { videoId: 'Nu9RVPTpDyA', title: 'Endless Love – Royal Albert Hall (Luther & Mariah)', duration: '5:18', date: '2012', views: '45M', category: 'Luther Vandross & Mariah Carey', description: 'Live duet – classic love song' },
    { videoId: '3AtDnEC4zak', title: 'Unchained Melody – Live', duration: '3:58', date: '1990', views: '82M', category: 'Righteous Brothers', description: 'Grammy Hall of Fame' },
    { videoId: 'hT_nvWreIhg', title: 'Always – Live', duration: '4:20', date: '1994', views: '180M', category: 'Bon Jovi', description: 'Power ballad – Grammy nominated' },
    { videoId: 'fJ9rUzIMcZQ', title: 'Bohemian Rhapsody – Live Aid 1985', duration: '4:50', date: '1985', views: '1.2B', category: 'Queen', description: 'Legendary love/rock – historic' },
    { videoId: 'GBo2e4V5k8I', title: 'Because You Loved Me – Live Las Vegas', duration: '5:45', date: '2007', views: '6.2M', category: 'Celine Dion', description: 'Grammy winner – Best Song' },
    { videoId: 'GBF9K3f1VMc', title: "My Heart Will Go On – Live in Las Vegas", duration: '5:30', date: '2007', views: '13M', category: 'Celine Dion', description: 'Grammy Record of the Year' },
  ],

  playlist: [
    { videoId: 'DUT5rEU6pqM', title: 'Shakira 4K Dance & Live', duration: '5:00', date: '2023', views: '2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'weRHyjj34ZE', title: 'Shakira 4K Performance', duration: '6:15', date: '2023', views: '1.5M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'Dsp_8Lm1eSk', title: 'Shakira Live 4K', duration: '4:30', date: '2022', views: '3M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'booKP974B0k', title: 'Shakira 4K Energy', duration: '7:00', date: '2024', views: '1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'Ntn1-SocNiY', title: 'Shakira Best 4K Live', duration: '5:45', date: '2023', views: '2.2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'XkYAxGt-aUs', title: 'Shakira Dance 4K', duration: '6:20', date: '2022', views: '1.8M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'XAhTt60W7qo', title: 'Shakira Live Performance', duration: '4:55', date: '2024', views: '900K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'KewfYKJy8YU', title: 'Shakira 4K Live', duration: '5:30', date: '2023', views: '1.2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'a5irTX82olg', title: 'Shakira Energy 4K', duration: '6:00', date: '2022', views: '1.5M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'QrOe2h9RtWI', title: 'Shakira Best Dance', duration: '5:15', date: '2024', views: '800K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'o3mP3mJDL2k', title: 'Shakira 4K Concert', duration: '7:20', date: '2023', views: '1.1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'vMLk_T0PPbk', title: 'Shakira Live 4K HD', duration: '5:45', date: '2022', views: '1.9M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '6Mgqbai3fKo', title: 'Shakira Dance Live', duration: '4:40', date: '2024', views: '700K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '7-7knsP2n5w', title: 'Shakira 4K Full', duration: '6:30', date: '2023', views: '1.3M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'sPTn0QEhxds', title: 'Shakira Best Live', duration: '5:50', date: '2022', views: '1.6M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'SHq2qrFUlGY', title: 'Shakira 4K Energy Live', duration: '4:25', date: '2024', views: '600K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '4I25nV9hXGA', title: 'Shakira Concert 4K', duration: '7:10', date: '2023', views: '1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
  ],

  african: [
    { videoId: 'ZhdprvzfTXg', title: 'Fela Kuti – Live Glastonbury 1984', duration: '1:01:04', date: '1984', views: '500K+', category: 'African', description: 'Afrobeat legend' },
    { videoId: 'sUqIR_DpPkA', title: 'Femi Kuti – North Sea Jazz 1999', duration: '1:14:55', date: '1999', views: '300K+', category: 'African', description: 'Afrobeat' },
    { videoId: '7of6faOge2o', title: 'Burna Boy – YouTube Music Nights London 2024', duration: '1:12:55', date: '2024', views: '1.4M', category: 'African', description: 'Afrofusion' },
    { videoId: 'PItnw3Z7WgY', title: 'Tinariwen – KEXP 2017', duration: '26:13', date: '2017', views: '4.9M', category: 'African', description: 'Desert Blues' },
    { videoId: 'RX6NCE-wz3s', title: "Youssou N'Dour – North Sea Jazz", duration: '1:23:56', date: '2008', views: '150K+', category: 'African', description: 'Mbalax' },
    { videoId: 'VZZoGkI71OA', title: 'Angélique Kidjo – Live Concert', duration: '1:12:19', date: '2019', views: '50K+', category: 'African', description: 'West African' },
    { videoId: '7pvCINz3N6Y', title: 'Bombino – KEXP 2023', duration: '31:57', date: '2023', views: '138K', category: 'African', description: 'Desert Blues' },
    { videoId: '4mnAUe4c08o', title: 'Ali Farka Touré – Brussels 2005', duration: '7:23', date: '2005', views: '500K+', category: 'African', description: 'Malian Blues' },
    { videoId: 'dQtibyqDyZE', title: 'Oumou Sangaré – Live', duration: '1:16:46', date: '2018', views: '1M', category: 'African', description: 'Wassoulou' },
    { videoId: 'KUm6f0QJ_FI', title: 'Omar Sosa & Seckou Keita – Tiny Desk', duration: '22:07', date: '2023', views: '300K+', category: 'African', description: 'Kora/Jazz' },
  ],

  latin: [
    { videoId: 'a9RmhRUab7g', title: 'Ibrahim Ferrer – North Sea Jazz 2005', duration: '1:13:35', date: '2005', views: '500K+', category: 'Latin/Cuban', description: 'Cuban Son/Bolero' },
    { videoId: 'vPIsI__b-IQ', title: 'BVSC ft. Omara Portuondo – North Sea Jazz 2008', duration: '1:23:10', date: '2008', views: '300K+', category: 'Latin/Cuban', description: 'Cuban Son' },
    { videoId: 'ePpEn9sh8Xg', title: 'Celia Cruz & Oscar D\'Leon – North Sea Jazz 2000', duration: '1:16:34', date: '2000', views: '1M', category: 'Latin/Cuban', description: 'Salsa' },
    { videoId: 'tAB2Depg5kk', title: 'Celia Cruz y Willie Colón – 1980 Capitol Theatre', duration: '50:11', date: '1980', views: '800K', category: 'Latin/Cuban', description: 'Salsa Dura' },
    { videoId: '-NScSbZ-S7c', title: "Fania All Stars – Puerto Rico '94", duration: '1:33:27', date: '1994', views: '2M', category: 'Latin/Cuban', description: 'Salsa' },
    { videoId: 'ylBIyQaraSA', title: 'Ruben Blades – Capitol Theatre 1980', duration: '53:10', date: '1980', views: '600K', category: 'Latin/Cuban', description: 'Salsa Consciente' },
    { videoId: 'bjWGcoVNNZ4', title: 'Tito Puente – Blue Note Japan', duration: '1:21:49', date: '1990', views: '400K', category: 'Latin/Cuban', description: 'Latin Jazz' },
    { videoId: 'Sqh7JRKD1E8', title: 'Tito Puente – Umbria Jazz Festival', duration: '50:09', date: '1992', views: '350K', category: 'Latin/Cuban', description: 'Mambo' },
    { videoId: 'X1bx9_TL20A', title: 'Buena Vista Social Club – Tiny Desk', duration: '20:19', date: '2020', views: '1.5M', category: 'Latin/Cuban', description: 'Cuban Son' },
    { videoId: 'XerTuv79p2M', title: 'Carlos Vives – Tiny Desk', duration: '28:37', date: '2019', views: '2M', category: 'Latin/Cuban', description: 'Vallenato' },
  ],

  flamenco: [
    { videoId: 'cFlDf7Ck-N4', title: 'Al Di Meola, McLaughlin, Paco De Lucia – Warfield 1980', duration: '2:24:19', date: '1980', views: '1.5M', category: 'Flamenco', description: 'Flamenco Fusion' },
    { videoId: 'erZZSsjvUmI', title: 'Paco De Lucía – North Sea Jazz 2006', duration: '1:06:30', date: '2006', views: '500K+', category: 'Flamenco', description: 'Full concert' },
    { videoId: 'WdZpf-w4_4o', title: 'Paco de Lucia & Group – Germany 1996', duration: '1:19:22', date: '1996', views: '794K', category: 'Flamenco', description: 'Flamenco Nuevo' },
    { videoId: 'CJuHHNtcxd8', title: 'Paco de Lucia Sextet – Concert 1988', duration: '57:58', date: '1988', views: '200K+', category: 'Flamenco', description: 'Flamenco Nuevo' },
    { videoId: 'AXtbqtYhH1Y', title: 'Camarón de la Isla & Tomatito – Montreux 1991', duration: '54:56', date: '1991', views: '700K+', category: 'Flamenco', description: 'Cante Jondo' },
    { videoId: 'xzjLPClOCIY', title: 'Vicente Amigo – Jazz à Sète 2014', duration: '20:12', date: '2014', views: '14K', category: 'Flamenco', description: 'Flamenco' },
    { videoId: 'kmaOa8xo9C8', title: 'Vicente Amigo – 4K Live Istanbul 2025', duration: '10:43', date: '2025', views: '3.1K', category: 'Flamenco', description: '4K' },
    { videoId: 'ls72UT1HsP0', title: 'Rodrigo y Gabriela – Ancienne Belgique 2009', duration: '1:40:55', date: '2009', views: '865K', category: 'Flamenco', description: 'Flamenco Fusion' },
    { videoId: '6343H42j_YI', title: 'Jesse Cook – PBS Special 2012', duration: '1:00:04', date: '2012', views: '1.2M', category: 'Flamenco', description: 'Nouveau Flamenco' },
    { videoId: 'g5MGa524r3A', title: 'Flamenco Tablao – Barcelona 4K', duration: '28:57', date: '2022', views: '200K+', category: 'Flamenco', description: 'Authentic tablao' },
  ],
};
