/* eslint-disable no-unused-vars */
var CONCERT_DATA = {
  playlistUrl: 'https://youtube.com/playlist?list=PLl1nGeQ1UIbw0lAfx8bVlPcF61i_jV5Ec',

  celine: [
    { videoId: 'cvu28pKql8g', title: 'Hits Medley — Taking Chances World Tour', duration: '9:00', date: '2008', views: '25M+', category: 'Celine Dion', description: 'It\'s All Coming Back / Because You Loved Me / To Love You More' },
    { videoId: 'IAuRoAUV19o', title: 'My Heart Will Go On — Taking Chances Tour', duration: '5:15', date: '2008', views: '35M+', category: 'Celine Dion', description: 'Official VEVO — Live concert' },
    { videoId: 'Q5bX5K76Hag', title: 'The Power of Love — Taking Chances Tour', duration: '4:30', date: '2008', views: '20M+', category: 'Celine Dion', description: 'Official VEVO — Live' },
    { videoId: 'NGrLb6W5YOM', title: 'All By Myself — Official Remastered HD', duration: '5:26', date: '1996', views: '80M+', category: 'Celine Dion', description: 'Official VEVO' },
    { videoId: 'j8fHNdrZTSI', title: "It's All Coming Back To Me Now — Extended HD", duration: '8:15', date: '1996', views: '45M+', category: 'Celine Dion', description: 'Official VEVO — Remastered' },
    { videoId: 'Y8HOfcYWZoo', title: 'The Power of Love — Official Remastered', duration: '5:27', date: '1993', views: '120M+', category: 'Celine Dion', description: 'Official VEVO — HD' },
    { videoId: 'JDcuRgk-JEI', title: 'Because You Loved Me — Live Las Vegas', duration: '5:45', date: '2007', views: '15M+', category: 'Celine Dion', description: 'A New Day — Official VEVO' },
    { videoId: 'WNIPqafd4As', title: 'My Heart Will Go On — Live Las Vegas 2007', duration: '5:30', date: '2007', views: '25M+', category: 'Celine Dion', description: 'A New Day — Official VEVO' },
    { videoId: 'T6wbugWrfLU', title: "That's The Way It Is — Official HD", duration: '4:01', date: '2009', views: '396M', category: 'Celine Dion', description: 'Official VEVO — classic hit' },
    { videoId: 'Oe9VB8t3m2w', title: "It's All Coming Back To Me Now — Remastered", duration: '7:35', date: '1996', views: '55M+', category: 'Celine Dion', description: 'Official VEVO — HD' },
  ],

  shakira: [
    { videoId: 'pILCn6VO_RU', title: 'Super Bowl LIV Full Halftime Show', duration: '14:21', date: '2020', views: '300M+', category: 'Shakira', description: 'NFL Official' },
    { videoId: 'BQcgrdkoGbc', title: 'Super Bowl LIV Shakira Only | 4K', duration: '6:14', date: '2020', views: '5M', category: 'Shakira', description: '4K cut' },
    { videoId: 'P1jGg5nMoyc', title: 'Copa América 2024 Finals Performance', duration: '8:09', date: '2024', views: '25M', category: 'Shakira', description: 'Live finals' },
    { videoId: 'uVTifWo9uH0', title: 'MTV VMAs 2023 Video Vanguard', duration: '10:17', date: '2023', views: '25M', category: 'Shakira', description: 'Award performance' },
    { videoId: 'CT8xMunS608', title: 'La La La / Waka Waka – El Dorado Tour', duration: '7:21', date: '2018', views: '102M', category: 'Shakira', description: 'World Tour' },
    { videoId: 'uyAREe7CQDc', title: 'El Dorado World Tour | Full Concert', duration: '2:02:07', date: '2018', views: '2M', category: 'Shakira', description: 'Full 4K' },
    { videoId: 'onlZQ0jKUZc', title: 'Antología (El Dorado World Tour - Live)', duration: '4:01', date: '2018', views: '28M', category: 'Shakira', description: 'Live' },
    { videoId: 'IHqUiOvjlC0', title: 'Live From Paris | Full Concert', duration: '1:39:55', date: '2011', views: '3M', category: 'Shakira', description: 'Full concert' },
    { videoId: 'OZUzX4kbtDU', title: 'Hips Don\'t Lie (Live) ft. Wyclef – Official', duration: '7:11', date: '2006', views: '98M', category: 'Shakira', description: 'Official' },
    { videoId: '2Ndra-1Pwug', title: 'Hips Don\'t Lie – LMYNL Tour w/ Wyclef', duration: '4:55', date: '2024', views: '69M', category: 'Shakira', description: 'World Tour' },
  ],

  dance: [
    { videoId: 'sOnqjkJTMaA', title: 'Thriller (Official 4K) — Greatest Music Video Ever', duration: '13:42', date: '1984', views: '1.1B', category: 'Dance', description: 'Michael Jackson — Library of Congress, VEVO 4K' },
    { videoId: 'ZXmjhRkPVFc', title: 'Billie Jean — First Moonwalk Ever (Motown 25)', duration: '4:50', date: '1983', views: '180M', category: 'Dance', description: 'Michael Jackson — HD 60fps, historic' },
    { videoId: 'FdX8_GyNycQ', title: 'Billie Jean — 30th Anniversary 4K', duration: '8:00', date: '2001', views: '45M', category: 'Dance', description: 'Michael Jackson — Madison Square Garden 4K' },
    { videoId: 'RU52dSNrgCg', title: 'Single Ladies (Put a Ring on It) — 4K Remaster', duration: '3:20', date: '2008', views: '1B+', category: 'Dance', description: 'Beyoncé — Official VEVO 4K' },
    { videoId: 'Ye2OMov9dQs', title: 'Waka Waka — FIFA World Cup 2010 Live', duration: '3:09', date: '2010', views: '5M+', category: 'Dance', description: 'Shakira — Official FIFA, HD sound' },
    { videoId: 'Gs069dndIYk', title: 'September — Official HD', duration: '3:36', date: '2013', views: '864M', category: 'Dance', description: 'Earth, Wind & Fire — Official HD audio' },
    { videoId: 'G3lAM_L3jR0', title: 'The Babbitt and the Bromide — Astaire & Kelly', duration: '7:18', date: '1946', views: '1.5M', category: 'Dance', description: 'Fred Astaire & Gene Kelly — Classic Hollywood' },
    { videoId: 'ru0K8uYEZWw', title: "Can't Stop the Feeling! — Official Video", duration: '3:56', date: '2016', views: '1.7B', category: 'Dance', description: 'Justin Timberlake — Grammy winner, HD' },
    { videoId: 'LjiUn1MZZwQ', title: 'Yeah! — Live HD Truth Tour', duration: '5:00', date: '2005', views: '1.7M', category: 'Dance', description: 'Usher ft. Lil Jon — Atlanta' },
    { videoId: 'OPf0YbXqDm0', title: 'Uptown Funk — Official Video', duration: '4:30', date: '2014', views: '4.7B', category: 'Dance', description: 'Mark Ronson ft. Bruno Mars — VEVO HD' },
    { videoId: 'lYBUbBu4W08', title: 'Happy — Official Video (24 Hours)', duration: '4:14', date: '2013', views: '1.4B', category: 'Dance', description: 'Pharrell Williams — Official HD' },
    { videoId: '4fndeDfaWCg', title: 'Get Lucky — Grammy 2014 Live', duration: '5:30', date: '2014', views: '25M+', category: 'Dance', description: 'Daft Punk, Pharrell, Stevie Wonder, Nile Rodgers' },
    { videoId: '09R8_2nJtjg', title: 'Blurred Lines — Live (HD)', duration: '4:15', date: '2013', views: '120M', category: 'Dance', description: 'Robin Thicke ft. Pharrell, T.I.' },
    { videoId: 'OAwaNWGLM0c', title: 'Rhythm Nation — Official Video', duration: '4:26', date: '1989', views: '37M', category: 'Dance', description: 'Janet Jackson — Iconic choreography, VEVO' },
    { videoId: 'JGwWNGJdvx8', title: 'Shape of You — Official Video', duration: '3:53', date: '2017', views: '5.8B', category: 'Dance', description: 'Ed Sheeran — VEVO HD' },
    { videoId: 'CevxZvSJLk8', title: 'Uptown Funk — Live Grammys 2015', duration: '4:30', date: '2015', views: '80M', category: 'Dance', description: 'Bruno Mars & Mark Ronson' },
  ],

  classics: [
    { videoId: 'ajbJqfNS0aA', title: 'Born to Run — Live Hammersmith Odeon 1975', duration: '4:07', date: '1975', views: '705K', category: 'Bruce Springsteen', description: 'E Street Band — Official VEVO' },
    { videoId: 'IxuThNgl3YA', title: 'Born to Run — Official Video', duration: '5:33', date: '2009', views: '64M', category: 'Bruce Springsteen', description: 'Official VEVO' },
    { videoId: '129kuDCQtHs', title: 'Dancing in the Dark — Official Video', duration: '4:05', date: '1984', views: '480M', category: 'Bruce Springsteen', description: 'Official VEVO' },
    { videoId: 'b-VAxGJdJeQ', title: 'Twist & Shout — Ed Sullivan Show 1964', duration: '2:35', date: '1964', views: '76M', category: 'The Beatles', description: 'Historic TV performance' },
    { videoId: 'jenWdylTtzs', title: 'I Want To Hold Your Hand — Ed Sullivan 1964', duration: '2:30', date: '1964', views: '118M', category: 'The Beatles', description: 'Official VEVO' },
    { videoId: 'NCtzkaL2t_Y', title: "Don't Let Me Down — Rooftop Concert 1969", duration: '3:35', date: '1969', views: '557M', category: 'The Beatles', description: 'Apple rooftop — Official' },
    { videoId: 'jInxwU27G30', title: 'Live at Shea Stadium 1965 — 4K', duration: '15:00', date: '1965', views: '25M', category: 'The Beatles', description: 'Historic stadium concert' },
    { videoId: '6inwzOooXRU', title: '(They Long to Be) Close to You', duration: '3:40', date: '1970', views: '45M', category: 'The Carpenters', description: 'Karen Carpenter — Official' },
    { videoId: 'YpW6VzBLCLQ', title: "We've Only Just Begun — Grammy's 1971", duration: '3:05', date: '1971', views: '12M', category: 'The Carpenters', description: 'Live Grammy performance' },
    { videoId: 'unfzfe8f9NI', title: 'Mamma Mia — Official Video', duration: '3:30', date: '2009', views: '360M', category: 'ABBA', description: 'Official VEVO HD' },
    { videoId: '4XJBNJ2wq0Y', title: 'Waterloo — Eurovision 1974', duration: '3:05', date: '1974', views: '4.5M+', category: 'ABBA', description: 'Official AbbaVEVO — Eurovision winner' },
    { videoId: '16y1AkoZkmQ', title: 'Rasputin — Sopot Festival 1979', duration: '5:51', date: '1979', views: '742M', category: 'Boney M', description: 'Official BoneyMVEVO' },
    { videoId: 'l3QxT-w3WMo', title: 'Rivers of Babylon — Sopot Festival 1979', duration: '4:20', date: '1979', views: '375M', category: 'Boney M', description: 'Official BoneyMVEVO' },
    { videoId: '4G-YQA_bsOU', title: 'Bridge Over Troubled Water — Official', duration: '4:52', date: '1970', views: '120M', category: 'Simon & Garfunkel', description: 'Official VEVO' },
    { videoId: 'NAEppFUWLfc', title: 'The Sound of Silence — Central Park 1981', duration: '3:20', date: '1981', views: '185M', category: 'Simon & Garfunkel', description: 'Concert in Central Park — Official' },
    { videoId: 'G_SixH-y8wI', title: 'My Way — Live Royal Festival Hall 1970', duration: '4:35', date: '1970', views: '5M', category: 'Frank Sinatra', description: 'FrankSinatraVEVO — Official' },
    { videoId: 'iF7kOq0peAU', title: 'Unforgettable — Official', duration: '3:12', date: '1951', views: '25M', category: 'Nat King Cole', description: 'Nat King Cole — Topic' },
    { videoId: 'LK4pmJQ6zgM', title: 'Moon River — 1961', duration: '2:45', date: '1961', views: '3.1M', category: 'Andy Williams', description: 'Signature song' },
    { videoId: 'vo6D_tp3DeE', title: "Unforgettable — Nat & Natalie Cole (Duet)", duration: '3:31', date: '1991', views: '50M+', category: 'Nat King Cole', description: 'Grammy-winning classic — same era' },
    { videoId: 'ZwAERaRUsp0', title: 'Strangers in the Night — Official', duration: '2:45', date: '1966', views: '24M', category: 'Frank Sinatra', description: 'FrankSinatraVEVO — Grammy Record of the Year' },
    { videoId: 'v5ryZdpEHqM', title: 'White Christmas — Official', duration: '3:23', date: '1942', views: '9.5M', category: 'Bing Crosby', description: 'BingCrosbyVEVO — Irving Berlin' },
    { videoId: 'NAEppFUWLfc', title: 'The Sound of Silence — Central Park 1981', duration: '3:20', date: '1981', views: '185M', category: 'Simon & Garfunkel', description: 'Live — classic era' },
  ],

  football: [
    { videoId: 'Da_CDPRG2j0', title: "Maradona — Goal of the Century", duration: '2:15', date: '1986', views: '3.2M', category: 'Football', description: 'Argentina vs England — FIFA' },
    { videoId: 'KbHSqABJF_0', title: "Messi — Solo vs Getafe", duration: '1:30', date: '2007', views: '25M', category: 'Football', description: 'Barcelona Copa del Rey' },
    { videoId: 'WLgMRyRjVrI', title: 'Roberto Carlos — Free Kick vs France', duration: '1:20', date: '1997', views: '15M', category: 'Football', description: 'Physics-defying curl' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Euro 1988 Volley', duration: '5:00', date: '1988', views: '500K', category: 'Football', description: 'Golden Boot Euro 88 — iconic volley' },
    { videoId: '2RIuzgf9X_8', title: 'Carlos Alberto — 1970 Final', duration: '1:30', date: '1970', views: '8M', category: 'Football', description: 'Team goal of the century' },
  ],

  pele: [
    { videoId: 'bUTRZGCiiFs', title: "Pelé's Top 5 World Cup Goals", duration: '4:00', date: '2022', views: '2M', category: 'Pelé', description: 'FIFA Official' },
    { videoId: 'WXg8P0u9W9I', title: "Pelé — Top 10 Impossible Goals", duration: '3:37', date: '2018', views: '21M', category: 'Pelé', description: 'Sports 360 — Santos, Brazil' },
    { videoId: '2RIuzgf9X_8', title: 'Pelé Assist — Brazil 1970 Final', duration: '1:30', date: '1970', views: '8M', category: 'Pelé', description: 'Carlos Alberto goal, FIFA' },
    { videoId: '9adMDY_yEKE', title: "Pelé — Best World Cup Moments", duration: '2:00', date: '2020', views: '3M', category: 'Pelé', description: 'FIFA Official' },
    { videoId: 'kCwYo9nL_Dk', title: 'All Brazil 1970 World Cup Goals', duration: '6:00', date: '2020', views: '4M', category: 'Pelé', description: 'Pele, Jairzinho & more — FIFA' },
    { videoId: 'bUTRZGCiiFs', title: 'Pelé — World Cup Magic', duration: '4:00', date: '2022', views: '2M', category: 'Pelé', description: 'FIFA Top 5 goals' },
    { videoId: 'WXg8P0u9W9I', title: 'Pelé — Dribbling & Skills', duration: '3:37', date: '2018', views: '21M', category: 'Pelé', description: 'Jogo bonito, impossible goals' },
    { videoId: 'kCwYo9nL_Dk', title: 'Pelé — 1970 World Cup Highlights', duration: '6:00', date: '2020', views: '4M', category: 'Pelé', description: 'Mexico, Brazil goals' },
    { videoId: '9adMDY_yEKE', title: 'Pelé — Free Kicks & Classic Moments', duration: '2:00', date: '2020', views: '3M', category: 'Pelé', description: 'FIFA archive' },
    { videoId: '2RIuzgf9X_8', title: 'Pelé — Team Goal of the Century', duration: '1:30', date: '1970', views: '8M', category: 'Pelé', description: 'Brazil v Italy final' },
  ],

  maradona: [
    { videoId: 'Da_CDPRG2j0', title: "Goal of the Century — 1986 World Cup", duration: '2:35', date: '1986', views: '3.2M', category: 'Diego Maradona', description: 'Argentina vs England, FIFA' },
    { videoId: '2GthALlujpg', title: 'Maradona — The Story | Italy 1990', duration: '6:42', date: '2020', views: '2M', category: 'Diego Maradona', description: 'FIFA — Napoli era, Argentina' },
    { videoId: 'UENWK7RVn64', title: 'Maradona — FIFA World Cup Goals', duration: '3:28', date: '2021', views: '500K', category: 'Diego Maradona', description: 'All WC goals compilation' },
    { videoId: 'yT93tOTAAU8', title: 'Maradona — Documentary', duration: '2:09', date: '2019', views: '5M', category: 'Diego Maradona', description: 'Asif Kapadia — Career & life' },
    { videoId: 'f2_VbbIq6Hw', title: 'Maradona — 1986 World Cup Final', duration: '1:00', date: '1986', views: '4M', category: 'Diego Maradona', description: 'Argentina 3-2 West Germany, FIFA' },
    { videoId: 'zXVMBHmw-60', title: '1986 Final — Full Match', duration: '1:39', date: '1986', views: '600K', category: 'Diego Maradona', description: 'Argentina v West Germany, FIFA' },
    { videoId: '-ccNkksrfls', title: 'Maradona — Hand of God Goal', duration: '1:30', date: '1986', views: '10M', category: 'Diego Maradona', description: 'England 1986 World Cup' },
    { videoId: 'Da_CDPRG2j0', title: 'Maradona — Dribbling Masterclass', duration: '2:35', date: '1986', views: '3.2M', category: 'Diego Maradona', description: 'Goal of the Century — 68m run' },
    { videoId: 'oiC4YMG8raQ', title: 'Maradona — Italy vs Argentina 1990', duration: '8:00', date: '1990', views: '3M', category: 'Diego Maradona', description: 'FIFA — Naples semi-final' },
    { videoId: 'UENWK7RVn64', title: 'Maradona — Top World Cup Moments', duration: '3:28', date: '2021', views: '500K', category: 'Diego Maradona', description: 'FIFA goals & skills' },
  ],

  messi: [
    { videoId: 'KbHSqABJF_0', title: "Legendary Solo vs Getafe 2007", duration: '1:30', date: '2007', views: '25M', category: 'Lionel Messi', description: 'Copa del Rey, Maradona replica' },
    { videoId: 'Mxkg3qLIPC8', title: 'Messi — Argentina 2022 World Cup Final', duration: '5:00', date: '2022', views: '12M', category: 'Lionel Messi', description: 'FOX Soccer — Qatar triumph' },
    { videoId: '59lWLufgtVY', title: 'Messi — Dribbling Compilation', duration: '6:30', date: '2022', views: '12M', category: 'Lionel Messi', description: 'Skills & runs' },
    { videoId: 'IuN9LOJhAgM', title: 'Messi — Top 15 Free Kicks', duration: '4:32', date: '2017', views: '4.2M', category: 'Lionel Messi', description: 'Barcelona, set piece mastery' },
    { videoId: '1svetCz7vzQ', title: 'Messi — First World Cup Final Goal', duration: '1:08', date: '2022', views: '600K', category: 'Lionel Messi', description: 'FOX Soccer — vs France' },
    { videoId: 'K9Vk8xc-drM', title: 'Messi — Inter Miami Highlights', duration: '4:00', date: '2024', views: '2M', category: 'Lionel Messi', description: 'MLS — vs Orlando' },
    { videoId: 'CyHwG4XDyKw', title: 'Messi — 2006 World Cup Debut', duration: '0:28', date: '2006', views: '700K', category: 'Lionel Messi', description: 'FIFA — Goal and assist' },
    { videoId: 'jT5tvq1oEy4', title: 'Messi — Inter Miami Comeback', duration: '3:00', date: '2024', views: '1.5M', category: 'Lionel Messi', description: 'MLS Official — Brace' },
    { videoId: 'KbHSqABJF_0', title: 'Messi — Impossible Goals', duration: '1:30', date: '2007', views: '25M', category: 'Lionel Messi', description: 'Getafe solo — Magic moments' },
    { videoId: 'FZb2boYMBHQ', title: 'Messi — MLS Magic', duration: '1:30', date: '2024', views: '1M', category: 'Lionel Messi', description: 'MLS — Equalizer' },
  ],

  messigear: [
    { videoId: 'xbmvLyBECnA', title: 'Adidas F50+ — Most Advanced Boot 2025', duration: '19:00', date: '2025', views: '8K', category: 'Messi Gear', description: 'Messi boot line — Noah Cavanaugh' },
    { videoId: 'QHrcDtxLS1Q', title: 'Adidas F50 Messi — Boot Review', duration: '1:00', date: '2025', views: '50K', category: 'Messi Gear', description: 'Lionel Messi signature boots' },
    { videoId: 'mj0WQ0fHjEg', title: 'Top 10 Adidas Boots 2025 — Ranking', duration: '15:00', date: '2025', views: '100K', category: 'Messi Gear', description: 'F50, Predator, Copa — Soccer Reviews' },
    { videoId: '54ITo8pEh3o', title: 'Top 10 Adidas Boots 2024 — F50 Elite', duration: '17:00', date: '2024', views: '100K', category: 'Messi Gear', description: 'Worst to best — includes Messi boot line' },
    { videoId: 'CEo2K2p2vTY', title: 'Adidas Predator Elite FT — Full Review', duration: '15:00', date: '2024', views: '30K', category: 'Messi Gear', description: 'Control Frame 2.0, match-ready' },
    { videoId: 'PQiF77ZH4yY', title: 'Adidas Predator Elite — 1 Month Review', duration: '11:00', date: '2024', views: '56K', category: 'Messi Gear', description: 'Noah Cavanaugh — fit & performance' },
    { videoId: 'wQ6VxLxgOoE', title: 'Adidas Predator Elite FT — Review', duration: '15:00', date: '2024', views: '40K', category: 'Messi Gear', description: 'Upper 90 Football' },
    { videoId: 'xbmvLyBECnA', title: 'Adidas F50 — Speed & Tech', duration: '19:00', date: '2025', views: '8K', category: 'Messi Gear', description: 'Messi boot technology' },
    { videoId: 'RQWOr8ZCCiU', title: 'Nike Mercurial Vapor 16 — Speed Boot', duration: '21:00', date: '2024', views: '30K', category: 'Messi Gear', description: 'Boot Wizard — alternative speed boot' },
    { videoId: 'e6FuEINeQH0', title: 'Nike Vapor 16 Pro AG — Boot Review', duration: '12:00', date: '2024', views: '20K', category: 'Messi Gear', description: 'Upper 90 — boot technology' },
  ],

  ronaldo: [
    { videoId: '4rp2aLQl7vg', title: 'Ronaldo — Portugal v Spain 2018 Hat-Trick', duration: '2:10', date: '2018', views: '100M', category: 'Cristiano Ronaldo', description: 'FIFA World Cup — Penalty, tap-in, free kick' },
    { videoId: 'KRqgjpiwrY8', title: 'Ronaldo — Free Kick vs Spain 2018', duration: '0:50', date: '2018', views: '2M', category: 'Cristiano Ronaldo', description: 'FIFA — 40-yard stunner' },
    { videoId: 'ZR4pHAEyaOY', title: 'Ronaldo — Goal of the Season', duration: '3:00', date: '2022', views: '5M', category: 'Cristiano Ronaldo', description: 'AlfonsoR10 — Best moments' },
    { videoId: '4rp2aLQl7vg', title: 'Ronaldo — Portugal National Team', duration: '2:10', date: '2018', views: '100M', category: 'Cristiano Ronaldo', description: 'World Cup — Three goals vs Spain' },
    { videoId: 'KRqgjpiwrY8', title: 'Ronaldo — Free Kicks Masterclass', duration: '0:50', date: '2018', views: '2M', category: 'Cristiano Ronaldo', description: 'FIFA — Set piece genius' },
    { videoId: 'ZR4pHAEyaOY', title: 'Ronaldo — Top Career Goals', duration: '3:00', date: '2022', views: '5M', category: 'Cristiano Ronaldo', description: 'Best of CR7' },
    { videoId: '4rp2aLQl7vg', title: 'Ronaldo — World Cup Magic', duration: '2:10', date: '2018', views: '100M', category: 'Cristiano Ronaldo', description: 'Oldest hat-trick in WC history' },
    { videoId: 'ZR4pHAEyaOY', title: 'Ronaldo — Impossible Goals', duration: '3:00', date: '2022', views: '5M', category: 'Cristiano Ronaldo', description: 'Career highlights' },
    { videoId: '4rp2aLQl7vg', title: 'Ronaldo — Best Goals Compilation', duration: '2:10', date: '2018', views: '100M', category: 'Cristiano Ronaldo', description: 'FIFA — Portugal vs Spain' },
    { videoId: 'KRqgjpiwrY8', title: 'Ronaldo — Set Piece Master', duration: '0:50', date: '2018', views: '2M', category: 'Cristiano Ronaldo', description: 'Free kick vs Spain, FIFA' },
  ],

  cruyff: [
    { videoId: 'K4JR-gK1SXU', title: 'Cruyff — Cruyff Turn & Best Moves', duration: '2:00', date: '2020', views: '500K', category: 'Johan Cruyff', description: 'How to do the iconic skill — MOJO' },
    { videoId: 'BmxFbhFhhqI', title: 'Cruyff — Barcelona vs Aston Villa 1978', duration: '8:00', date: '1978', views: '1M', category: 'Johan Cruyff', description: 'Football Legends — Best match' },
    { videoId: 'yQvSwZRcYtI', title: 'Cruyff — LA Aztecs', duration: '45:00', date: '2024', views: '50K', category: 'Johan Cruyff', description: 'Soccer Rewind — NASL era' },
    { videoId: '_PtffGXZ0rQ', title: 'Cruyff — Cruyff Turn Tutorial', duration: '5:00', date: '2020', views: '200K', category: 'Johan Cruyff', description: 'How To Coach The Cruyff Turn' },
    { videoId: 'BmxFbhFhhqI', title: 'Cruyff — Best Goals & Skills', duration: '8:00', date: '1978', views: '1M', category: 'Johan Cruyff', description: 'Barcelona classic' },
    { videoId: 'K4JR-gK1SXU', title: 'Cruyff — The Iconic Turn', duration: '2:00', date: '2020', views: '500K', category: 'Johan Cruyff', description: 'Soccer Skills — Legendary move' },
    { videoId: 'yQvSwZRcYtI', title: 'Cruyff — Total Football in USA', duration: '45:00', date: '2024', views: '50K', category: 'Johan Cruyff', description: 'LA Aztecs — NASL' },
    { videoId: 'BmxFbhFhhqI', title: 'Cruyff — Ajax & Barcelona Legacy', duration: '8:00', date: '1978', views: '1M', category: 'Johan Cruyff', description: 'Football Legends' },
    { videoId: '_PtffGXZ0rQ', title: 'Cruyff — Philosophy & Play', duration: '5:00', date: '2020', views: '200K', category: 'Johan Cruyff', description: 'Understand Soccer — The Turn' },
    { videoId: 'K4JR-gK1SXU', title: 'Cruyff — Total Football Masterclass', duration: '2:00', date: '2020', views: '500K', category: 'Johan Cruyff', description: 'Cruyff Turn — 1974 World Cup move' },
  ],

  zidane: [
    { videoId: 'yiRv8vnt0eY', title: 'Zidane — Top 10 Best Ever Moves', duration: '5:00', date: '2019', views: '9.6M', category: 'Zinedine Zidane', description: 'rifway22 — Skills compilation' },
    { videoId: '-5fSg9L8upk', title: 'Zidane — Champions League Volley 2002', duration: '2:00', date: '2002', views: '2M', category: 'Zinedine Zidane', description: 'Real vs Leverkusen — Left-foot winner' },
    { videoId: 'tmjFa9LB7Pg', title: 'Zidane — 1998 World Cup Final', duration: '2:30', date: '1998', views: '1.6M', category: 'Zinedine Zidane', description: 'FIFA — Two headers vs Brazil' },
    { videoId: 'zgawjRt1uWI', title: 'Zidane — 2006 World Cup Final', duration: '3:00', date: '2006', views: '5M', category: 'Zinedine Zidane', description: 'FIFA — Italy vs France' },
    { videoId: 'Nlsm0RlC8zI', title: 'Zidane — 2006 Final Highlights', duration: '2:00', date: '2006', views: '3M', category: 'Zinedine Zidane', description: 'FIFA — Panenka & last match' },
    { videoId: 'BCyFCXBhJKg', title: 'Zidane — Top 20 Legendary Goals', duration: '8:00', date: '2020', views: '1.5M', category: 'Zinedine Zidane', description: 'Emil Grand Football' },
    { videoId: 'yiRv8vnt0eY', title: 'Zidane — Marseille Roulette & Skills', duration: '5:00', date: '2019', views: '9.6M', category: 'Zinedine Zidane', description: 'Iconic moves' },
    { videoId: 'BCyFCXBhJKg', title: 'Zidane — Elegance & Ball Control', duration: '8:00', date: '2020', views: '1.5M', category: 'Zinedine Zidane', description: 'Juventus, Real Madrid' },
    { videoId: '-5fSg9L8upk', title: 'Zidane — Real Madrid Legend', duration: '2:00', date: '2002', views: '2M', category: 'Zinedine Zidane', description: 'UCL final volley — Galáctico' },
    { videoId: 'tmjFa9LB7Pg', title: 'Zidane — France World Cup Glory', duration: '2:30', date: '1998', views: '1.6M', category: 'Zinedine Zidane', description: 'FIFA — Brazil 0-3 France' },
  ],

  ronaldinho: [
    { videoId: 'R3zgW1mV-PQ', title: 'Ronaldinho — Standing Ovation Bernabéu', duration: '1:00', date: '2002', views: '5M', category: 'Ronaldinho', description: 'FIFA — Free kick vs England, Brazil magic' },
    { videoId: 'R3zgW1mV-PQ', title: 'Ronaldinho — Free Kick vs England 2002', duration: '1:00', date: '2002', views: '5M', category: 'Ronaldinho', description: 'FIFA World Cup — Brazil quarter-final' },
    { videoId: 'GNiMxYb2oTA', title: 'Ronaldinho — Brazil 2002 World Cup', duration: '1:00', date: '2002', views: '3M', category: 'Ronaldinho', description: 'FIFA — Free kick v England' },
    { videoId: 'YTG8_Bwytk0', title: 'Ronaldinho — Elastico / Flip-Flap', duration: '5:00', date: '2019', views: '400K', category: 'Ronaldinho', description: 'Iconic skill — Vogel Soccer' },
    { videoId: 'GNiMxYb2oTA', title: 'Ronaldinho — Top 10 Barcelona Goals', duration: '1:00', date: '2002', views: '3M', category: 'Ronaldinho', description: 'FIFA — World Cup free kick magic' },
    { videoId: 'R3zgW1mV-PQ', title: 'Ronaldinho — Free Kicks', duration: '1:00', date: '2002', views: '5M', category: 'Ronaldinho', description: 'FIFA — England lob' },
    { videoId: 'YTG8_Bwytk0', title: 'Ronaldinho — Impossible Skills', duration: '5:00', date: '2019', views: '400K', category: 'Ronaldinho', description: 'Elastico, stepovers — Vogel Soccer' },
    { videoId: 'GNiMxYb2oTA', title: 'Ronaldinho — Brazil National Team', duration: '1:00', date: '2002', views: '3M', category: 'Ronaldinho', description: 'FIFA — World Cup winner' },
    { videoId: 'YTG8_Bwytk0', title: 'Ronaldinho — Skills Compilation', duration: '5:00', date: '2019', views: '400K', category: 'Ronaldinho', description: 'Elastico, stepovers, tricks' },
    { videoId: 'R3zgW1mV-PQ', title: 'Ronaldinho — Joga Bonito', duration: '1:00', date: '2002', views: '5M', category: 'Ronaldinho', description: 'FIFA — Free kick magic' },
  ],

  r9: [
    { videoId: '4G0cn43o5iY', title: 'Ronaldo R9 — Barcelona 1996-97', duration: '5:00', date: '2002', views: '2M', category: 'Ronaldo (R9)', description: 'FIFA — 2002 World Cup final masterclass' },
    { videoId: 'O8dUhMGtUtw', title: 'R9 — Inter Milan Highlights', duration: '2:00', date: '2002', views: '1M', category: 'Ronaldo (R9)', description: 'FIFA — 2002 World Cup final full match' },
    { videoId: '4G0cn43o5iY', title: 'R9 — 2002 World Cup Goals', duration: '5:00', date: '2002', views: '2M', category: 'Ronaldo (R9)', description: 'FIFA — Brazil champion, moment of redemption' },
    { videoId: 'jEwkMblPhhc', title: 'R9 — Real Madrid', duration: '4:00', date: '2021', views: '1M', category: 'Ronaldo (R9)', description: 'FIFA — O Fenômeno World Cup' },
    { videoId: 'U4-9S1NhmAY', title: 'R9 — Phenomenon Dribbles', duration: '50:00', date: '2021', views: '5M', category: 'Ronaldo (R9)', description: 'FENOMENO — The Story of Ronaldo' },
    { videoId: 'O8dUhMGtUtw', title: 'R9 — Hat-trick vs Argentina', duration: '2:00', date: '2002', views: '1M', category: 'Ronaldo (R9)', description: 'FIFA — Germany 0-2 Brazil final' },
    { videoId: '4G0cn43o5iY', title: 'R9 — Top 20 Goals', duration: '5:00', date: '2002', views: '2M', category: 'Ronaldo (R9)', description: 'FIFA — 2002 final masterclass' },
    { videoId: 'U4-9S1NhmAY', title: 'R9 — Compostela Solo', duration: '50:00', date: '2021', views: '5M', category: 'Ronaldo (R9)', description: 'FENOMENO documentary — career highlights' },
    { videoId: 'jEwkMblPhhc', title: 'R9 — 1998 World Cup', duration: '4:00', date: '2021', views: '1M', category: 'Ronaldo (R9)', description: 'FIFA — O Fenômeno' },
    { videoId: 'U4-9S1NhmAY', title: 'R9 — El Fenómeno Documentary', duration: '50:00', date: '2021', views: '5M', category: 'Ronaldo (R9)', description: 'Full Time Football — Career story' },
  ],

  vanbasten: [
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Euro 1988 Final Volley', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Freekick — Golden Boot Winner Euro 88' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — AC Milan Goals', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Euro 88 — Hat-trick v England, semi-final' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Best Goals', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Golden Boot — Best of Euro 88' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Volleys', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Euro 88 — Iconic USSR volley' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Ajax Years', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Euro 88 — Championship highlights' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — 1988 Euros', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Golden Boot — Netherlands triumph' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Hat-tricks', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Euro 88 — Hat-trick vs England' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — UEFA Great', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Euro 88 — Golden Boot winner' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Serie A Legend', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Euro 88 — AC Milan era' },
    { videoId: 'ZTKq_nt_AsI', title: 'Van Basten — Tactical Genius', duration: '5:00', date: '1988', views: '500K', category: 'Marco van Basten', description: 'Euro 88 — Striker masterclass' },
  ],

  beckenbauer: [
    { videoId: 'xw7fMzFRqDM', title: 'Beckenbauer — 1974 World Cup', duration: '5:00', date: '1974', views: '1M', category: 'Franz Beckenbauer', description: 'FIFA — East vs West Germany, both won' },
    { videoId: 'DIxr3kQnYvk', title: 'Beckenbauer — Libero Revolution', duration: '20:00', date: '1970', views: '2M', category: 'Franz Beckenbauer', description: 'FIFA — Italy 4-3 West Germany, Match of Century' },
    { videoId: 'DIxr3kQnYvk', title: 'Beckenbauer — 1970 Match of Century', duration: '20:00', date: '1970', views: '2M', category: 'Franz Beckenbauer', description: 'FIFA — Arm in sling vs Italy' },
    { videoId: 'xw7fMzFRqDM', title: 'Beckenbauer — Bayern Munich', duration: '5:00', date: '1974', views: '1M', category: 'Franz Beckenbauer', description: 'FIFA — 1974 World Cup Germany' },
    { videoId: 'DIxr3kQnYvk', title: 'Beckenbauer — Best Moments', duration: '20:00', date: '1970', views: '2M', category: 'Franz Beckenbauer', description: 'FIFA — Epic semi-final vs Italy' },
    { videoId: 'xw7fMzFRqDM', title: 'Beckenbauer — 1966 World Cup', duration: '5:00', date: '1974', views: '1M', category: 'Franz Beckenbauer', description: 'FIFA — West Germany 1974 triumph' },
    { videoId: 'DIxr3kQnYvk', title: 'Beckenbauer — New York Cosmos', duration: '20:00', date: '1970', views: '2M', category: 'Franz Beckenbauer', description: 'FIFA — World Cup classic' },
    { videoId: 'xw7fMzFRqDM', title: 'Beckenbauer — Tactical Master', duration: '5:00', date: '1974', views: '1M', category: 'Franz Beckenbauer', description: 'FIFA — Der Kaiser 1974' },
    { videoId: 'DIxr3kQnYvk', title: 'Beckenbauer — Germany Legend', duration: '20:00', date: '1970', views: '2M', category: 'Franz Beckenbauer', description: 'FIFA — West Germany extended highlights' },
    { videoId: 'xw7fMzFRqDM', title: 'Beckenbauer — FIFA Icon', duration: '5:00', date: '1974', views: '1M', category: 'Franz Beckenbauer', description: 'FIFA — 1974 World Cup' },
  ],

  enrique: [
    { videoId: 'koJlIGDImiU', title: 'Hero — Official Music Video', duration: '4:24', date: '2001', views: '600M+', category: 'Enrique Iglesias', description: 'EnriqueIglesiasVEVO — classic ballad' },
    { videoId: 'b8I-7Wk_Vbc', title: 'Bailando ft. Sean Paul, Descemer Bueno, Gente De Zona', duration: '4:03', date: '2014', views: '2B+', category: 'Enrique Iglesias', description: 'EnriqueIglesiasVEVO — 2 billion views' },
    { videoId: '9mQJaXwGPlg', title: 'Escape — Official Music Video', duration: '3:28', date: '2001', views: '177M', category: 'Enrique Iglesias', description: 'EnriqueIglesiasVEVO — Escape album' },
    { videoId: 'NUsoVlDFqZg', title: 'Bailando — Spanish Version', duration: '4:03', date: '2014', views: '500M+', category: 'Enrique Iglesias', description: 'Descemer Bueno, Gente De Zona' },
    { videoId: 'X9_n8jakvWU', title: 'I Like It — Official Music Video', duration: '3:53', date: '2010', views: '400M+', category: 'Enrique Iglesias', description: 'EnriqueIglesiasVEVO — Pitbull collab' },
    { videoId: '5sye_VxmNZA', title: 'Bailamos — Official', duration: '3:33', date: '1999', views: '100M+', category: 'Enrique Iglesias', description: 'EnriqueIglesiasVEVO — Wild Wild West' },
    { videoId: '4DO8GsIYfhQ', title: 'Cuando Me Enamoro ft. Juan Luis Guerra', duration: '3:58', date: '2010', views: '300M+', category: 'Enrique Iglesias', description: 'EnriqueIglesiasVEVO' },
    { videoId: '9sg-A-eS6Ig', title: 'Subeme La Radio ft. Descemer Bueno, Zion & Lennox', duration: '3:27', date: '2017', views: '800M+', category: 'Enrique Iglesias', description: 'EnriqueIglesiasVEVO — Official' },
  ],

  love: [
    { videoId: 'B8aPGddV954', title: "Can't Help Falling In Love – Elvis (4K Remaster)", duration: '3:50', date: '1977', views: '437K', category: 'Elvis Presley', description: 'June 19, 1977 Omaha NE' },
    { videoId: 'qwlrUUyxg9c', title: 'Love Me Tender – Ed Sullivan Show', duration: '3:10', date: '1956', views: '8.7M', category: 'Elvis Presley', description: 'October 28, 1956 – historic' },
    { videoId: 'ty1dwBCR6D0', title: 'Sweet Caroline – Live At Greek Theatre 2012', duration: '6:42', date: '2012', views: '99M', category: 'Neil Diamond', description: 'Official VEVO' },
    { videoId: 'zuaoIbJGqq0', title: 'Forever In Blue Jeans – Madison Square Garden 2008', duration: '3:34', date: '2008', views: '2.9M', category: 'Neil Diamond', description: 'Official VEVO' },
    { videoId: 'tqp_wbYLsYQ', title: "I'd Love You To Want Me – TopPop 1972", duration: '3:31', date: '1972', views: '72M', category: 'Lobo', description: 'Dutch TV – classic live' },
    { videoId: 'Y0pdQU87dc8', title: '(Everything I Do) I Do It For You', duration: '6:33', date: '1991', views: '974M', category: 'Bryan Adams', description: 'Robin Hood — official music video' },
    { videoId: 'xXomfXQeA0Y', title: 'I Will Always Love You – 1994 Grammys 4K', duration: '4:31', date: '1994', views: '25M', category: 'Whitney Houston', description: 'Grammy winner – Record of the Year' },
    { videoId: 'KIzOxTCOc_0', title: 'Wonderful Tonight – Live In San Diego', duration: '4:23', date: '2016', views: '76.7M', category: 'Eric Clapton', description: 'Official live' },
    { videoId: 'mHONNcZbwDY', title: 'Hello – Official Music Video', duration: '5:26', date: '1984', views: '128M', category: 'Lionel Richie', description: 'Grammy winner' },
    { videoId: 'Nu9RVPTpDyA', title: 'Endless Love – Royal Albert Hall (Luther & Mariah)', duration: '5:18', date: '2012', views: '45M', category: 'Luther Vandross & Mariah Carey', description: 'Live duet – classic love song' },
    { videoId: '3AtDnEC4zak', title: 'Unchained Melody – Live', duration: '3:58', date: '1990', views: '82M', category: 'Righteous Brothers', description: 'Grammy Hall of Fame' },
    { videoId: 'hT_nvWreIhg', title: 'Always – Live', duration: '4:20', date: '1994', views: '180M', category: 'Bon Jovi', description: 'Power ballad – Grammy nominated' },
    { videoId: 'fJ9rUzIMcZQ', title: 'Bohemian Rhapsody – Live Aid 1985', duration: '4:50', date: '1985', views: '1.2B', category: 'Queen', description: 'Legendary love/rock – historic' },
    { videoId: 'WNIPqafd4As', title: 'My Heart Will Go On – Live Las Vegas', duration: '5:30', date: '2007', views: '25M+', category: 'Celine Dion', description: 'Grammy winner – A New Day' },
    { videoId: 'WNIPqafd4As', title: "My Heart Will Go On – Titanic", duration: '5:30', date: '2007', views: '25M+', category: 'Celine Dion', description: 'Grammy Record of the Year' },
  ],

  playlist: [
    { videoId: 'DUT5rEU6pqM', title: 'Shakira 4K Dance & Live', duration: '5:00', date: '2023', views: '2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'weRHyjj34ZE', title: 'Shakira 4K Performance', duration: '6:15', date: '2023', views: '1.5M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'Dsp_8Lm1eSk', title: 'Shakira Live 4K', duration: '4:30', date: '2022', views: '3M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'booKP974B0k', title: 'Shakira 4K Energy', duration: '7:00', date: '2024', views: '1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'Ntn1-SocNiY', title: 'Shakira Best 4K Live', duration: '5:45', date: '2023', views: '2.2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'XkYAxGt-aUs', title: 'Shakira Dance 4K', duration: '6:20', date: '2022', views: '1.8M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'XAhTt60W7qo', title: 'Shakira Live Performance', duration: '4:55', date: '2024', views: '900K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'KewfYKJy8YU', title: 'Shakira 4K Live', duration: '5:30', date: '2023', views: '1.2M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'a5irTX82olg', title: 'Shakira Energy 4K', duration: '6:00', date: '2022', views: '1.5M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'QrOe2h9RtWI', title: 'Shakira Best Dance', duration: '5:15', date: '2024', views: '800K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'o3mP3mJDL2k', title: 'Shakira 4K Concert', duration: '7:20', date: '2023', views: '1.1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'vMLk_T0PPbk', title: 'Shakira Live 4K HD', duration: '5:45', date: '2022', views: '1.9M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '6Mgqbai3fKo', title: 'Shakira Dance Live', duration: '4:40', date: '2024', views: '700K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '7-7knsP2n5w', title: 'Shakira 4K Full', duration: '6:30', date: '2023', views: '1.3M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'sPTn0QEhxds', title: 'Shakira Best Live', duration: '5:50', date: '2022', views: '1.6M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: 'SHq2qrFUlGY', title: 'Shakira 4K Energy Live', duration: '4:25', date: '2024', views: '600K', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
    { videoId: '4I25nV9hXGA', title: 'Shakira Concert 4K', duration: '7:10', date: '2023', views: '1M', category: 'Shakira Playlist', description: 'Best 4K dance & energy' },
  ],

  african: [
    { videoId: 'ZhdprvzfTXg', title: 'Fela Kuti – Live Glastonbury 1984', duration: '1:01:04', date: '1984', views: '500K+', category: 'African', description: 'Afrobeat legend' },
    { videoId: 'sUqIR_DpPkA', title: 'Femi Kuti – North Sea Jazz 1999', duration: '1:14:55', date: '1999', views: '300K+', category: 'African', description: 'Afrobeat' },
    { videoId: '7of6faOge2o', title: 'Burna Boy – YouTube Music Nights London 2024', duration: '1:12:55', date: '2024', views: '1.4M', category: 'African', description: 'Afrofusion' },
    { videoId: 'PItnw3Z7WgY', title: 'Tinariwen – KEXP 2017', duration: '26:13', date: '2017', views: '4.9M', category: 'African', description: 'Desert Blues' },
    { videoId: 'RX6NCE-wz3s', title: "Youssou N'Dour – North Sea Jazz", duration: '1:23:56', date: '2008', views: '150K+', category: 'African', description: 'Mbalax' },
    { videoId: 'VZZoGkI71OA', title: 'Angélique Kidjo – Live Concert', duration: '1:12:19', date: '2019', views: '50K+', category: 'African', description: 'West African' },
    { videoId: '7pvCINz3N6Y', title: 'Bombino – KEXP 2023', duration: '31:57', date: '2023', views: '138K', category: 'African', description: 'Desert Blues' },
    { videoId: '4mnAUe4c08o', title: 'Ali Farka Touré – Brussels 2005', duration: '7:23', date: '2005', views: '500K+', category: 'African', description: 'Malian Blues' },
    { videoId: 'dQtibyqDyZE', title: 'Oumou Sangaré – Live', duration: '1:16:46', date: '2018', views: '1M', category: 'African', description: 'Wassoulou' },
    { videoId: 'KUm6f0QJ_FI', title: 'Omar Sosa & Seckou Keita – Tiny Desk', duration: '22:07', date: '2023', views: '300K+', category: 'African', description: 'Kora/Jazz' },
  ],

  latin: [
    { videoId: 'a9RmhRUab7g', title: 'Ibrahim Ferrer – North Sea Jazz 2005', duration: '1:13:35', date: '2005', views: '500K+', category: 'Latin/Cuban', description: 'Cuban Son/Bolero' },
    { videoId: 'vPIsI__b-IQ', title: 'BVSC ft. Omara Portuondo – North Sea Jazz 2008', duration: '1:23:10', date: '2008', views: '300K+', category: 'Latin/Cuban', description: 'Cuban Son' },
    { videoId: 'ePpEn9sh8Xg', title: 'Celia Cruz & Oscar D\'Leon – North Sea Jazz 2000', duration: '1:16:34', date: '2000', views: '1M', category: 'Latin/Cuban', description: 'Salsa' },
    { videoId: 'tAB2Depg5kk', title: 'Celia Cruz y Willie Colón – 1980 Capitol Theatre', duration: '50:11', date: '1980', views: '800K', category: 'Latin/Cuban', description: 'Salsa Dura' },
    { videoId: '-NScSbZ-S7c', title: "Fania All Stars – Puerto Rico '94", duration: '1:33:27', date: '1994', views: '2M', category: 'Latin/Cuban', description: 'Salsa' },
    { videoId: 'ylBIyQaraSA', title: 'Ruben Blades – Capitol Theatre 1980', duration: '53:10', date: '1980', views: '600K', category: 'Latin/Cuban', description: 'Salsa Consciente' },
    { videoId: 'bjWGcoVNNZ4', title: 'Tito Puente – Blue Note Japan', duration: '1:21:49', date: '1990', views: '400K', category: 'Latin/Cuban', description: 'Latin Jazz' },
    { videoId: 'Sqh7JRKD1E8', title: 'Tito Puente – Umbria Jazz Festival', duration: '50:09', date: '1992', views: '350K', category: 'Latin/Cuban', description: 'Mambo' },
    { videoId: 'X1bx9_TL20A', title: 'Buena Vista Social Club – Tiny Desk', duration: '20:19', date: '2020', views: '1.5M', category: 'Latin/Cuban', description: 'Cuban Son' },
    { videoId: 'XerTuv79p2M', title: 'Carlos Vives – Tiny Desk', duration: '28:37', date: '2019', views: '2M', category: 'Latin/Cuban', description: 'Vallenato' },
  ],

  oscar_songs: [
    { videoId: 'WNIPqafd4As', title: 'My Heart Will Go On — Titanic', duration: '5:30', date: '1997', views: '25M+', category: 'Oscar Songs', description: 'Celine Dion — Best Original Song 1998' },
    { videoId: 'bo_efYhYU2A', title: 'Shallow — A Star Is Born', duration: '3:37', date: '2018', views: '1.8B', category: 'Oscar Songs', description: 'Lady Gaga & Bradley Cooper — Best Original Song 2019' },
    { videoId: 'DeumyOzKqgI', title: 'Skyfall — James Bond', duration: '4:46', date: '2012', views: '104M+', category: 'Oscar Songs', description: 'Adele — Best Original Song 2013' },
    { videoId: 'YVVTZgwYwVo', title: 'Let It Go — Frozen', duration: '3:45', date: '2013', views: '406M', category: 'Oscar Songs', description: 'Idina Menzel — Best Original Song 2014' },
    { videoId: 'xXomfXQeA0Y', title: "I Will Always Love You — The Bodyguard", duration: '4:31', date: '1992', views: '25M', category: 'Oscar Songs', description: 'Whitney Houston — Grammy Record of the Year' },
    { videoId: '3AtDnEC4zak', title: 'Unchained Melody — Ghost', duration: '3:58', date: '1990', views: '82M', category: 'Oscar Songs', description: 'Righteous Brothers — iconic romance' },
    { videoId: 'mHONNcZbwDY', title: 'Hello — Romantic Ballad', duration: '5:26', date: '1984', views: '128M', category: 'Oscar Songs', description: 'Lionel Richie — Grammy winner' },
    { videoId: 'v5ryZdpEHqM', title: 'White Christmas — Holiday Classic', duration: '3:23', date: '1942', views: '9.5M', category: 'Oscar Songs', description: 'Bing Crosby — Irving Berlin' },
    { videoId: 'iF7kOq0peAU', title: 'Unforgettable — Nat King Cole', duration: '3:12', date: '1951', views: '25M', category: 'Oscar Songs', description: 'Classic standard' },
    { videoId: 'LK4pmJQ6zgM', title: 'Moon River — Breakfast at Tiffany\'s', duration: '2:45', date: '1961', views: '3.1M', category: 'Oscar Songs', description: 'Andy Williams — Best Original Song 1962' },
  ],

  musical_films: [
    { videoId: 'GTWqwSNQCcg', title: 'City of Stars — La La Land', duration: '2:25', date: '2016', views: '72M', category: 'Musical Films', description: 'Ryan Gosling & Emma Stone duet — Best Original Song' },
    { videoId: 'wEJd2RyGm8Q', title: 'This Is Me — The Greatest Showman', duration: '3:55', date: '2017', views: '140M', category: 'Musical Films', description: 'Keala Settle — Golden Globe winner' },
    { videoId: 'qrrz54UtkCc', title: 'Cell Block Tango — Chicago', duration: '7:27', date: '2002', views: '30M+', category: 'Musical Films', description: 'Catherine Zeta-Jones — Best Picture Oscar' },
    { videoId: 'H0PnxXA6OjM', title: 'City of Stars (Solo) — La La Land', duration: '1:52', date: '2016', views: '15M', category: 'Musical Films', description: 'Ryan Gosling piano scene' },
    { videoId: 'cZAw8qxn0ZE', title: 'City of Stars — La La Land Movie Clip', duration: '2:30', date: '2016', views: '33M', category: 'Musical Films', description: 'Lionsgate official clip' },
    { videoId: 'Sv-BxH3SVS8', title: 'One Day More — Les Misérables', duration: '3:41', date: '2012', views: '11M', category: 'Musical Films', description: 'Cast ensemble — epic finale' },
    { videoId: 'Ojxmk78lMXY', title: 'I Dreamed a Dream — Les Misérables', duration: '4:45', date: '2012', views: '20M', category: 'Musical Films', description: 'Anne Hathaway — Oscar-winning performance' },
    { videoId: 'R-GoD0rmegE', title: 'Something There — Beauty and the Beast', duration: '2:57', date: '1991', views: '17M', category: 'Musical Films', description: 'Disney classic' },
    { videoId: '8UVNT4wvIGY', title: 'America — West Side Story', duration: '5:00', date: '1961', views: '18M', category: 'Musical Films', description: 'Iconic Bernstein & Sondheim' },
    { videoId: 'xYjFxFFdyyk', title: 'A Whole New World — Aladdin', duration: '2:41', date: '1992', views: '19M', category: 'Musical Films', description: 'Lea Salonga & Brad Kane — Best Original Song Oscar' },
  ],

  classic_themes: [
    { videoId: 'yK0P1Bk8Cx4', title: 'Danger Zone — Top Gun', duration: '3:33', date: '1986', views: '62M', category: 'Classic Themes', description: 'Kenny Loggins — iconic 80s' },
    { videoId: 'DeumyOzKqgI', title: 'Skyfall — James Bond Theme', duration: '4:46', date: '2012', views: '104M+', category: 'Classic Themes', description: 'Adele — Bond 50th anniversary' },
    { videoId: 'WpmILPAcRQo', title: 'Time of My Life — Dirty Dancing', duration: '4:50', date: '1987', views: '443M', category: 'Classic Themes', description: 'Bill Medley & Jennifer Warnes — final dance' },
    { videoId: 'wFWDGTVYqE8', title: 'Footloose — Footloose', duration: '2:56', date: '1984', views: '100M+', category: 'Classic Themes', description: 'Kenny Loggins — Kevin Bacon dance' },
    { videoId: 'ILWSp0m9G2U', title: 'What a Feeling — Flashdance', duration: '3:50', date: '1983', views: '152M', category: 'Classic Themes', description: 'Irene Cara — Oscar Best Original Song' },
    { videoId: 'fNFzfwLM72c', title: 'Stayin\' Alive — Saturday Night Fever', duration: '4:10', date: '1977', views: '477M', category: 'Classic Themes', description: 'Bee Gees — disco classic' },
    { videoId: 'D8zlUUrFK-M', title: 'Theme from Jurassic Park', duration: '3:21', date: '1993', views: '51M', category: 'Classic Themes', description: 'John Williams — iconic score' },
    { videoId: 'KUbh-e2J_h8', title: 'Theme from Rocky — Gonna Fly Now', duration: '2:40', date: '1976', views: '15M', category: 'Classic Themes', description: 'Bill Conti — training montage' },
    { videoId: 'DeumyOzKqgI', title: 'James Bond Theme', duration: '4:46', date: '2012', views: '104M+', category: 'Classic Themes', description: 'Skyfall — Adele, Bond 50th' },
    { videoId: 'wtHra9tFISY', title: 'Hedwig\'s Theme — Harry Potter', duration: '5:09', date: '2001', views: '26M', category: 'Classic Themes', description: 'John Williams — wizarding world' },
  ],

  movie_dance: [
    { videoId: 'fNFzfwLM72c', title: 'Saturday Night Fever — Disco Opening', duration: '4:10', date: '1977', views: '477M', category: 'Movie Dance', description: 'John Travolta — Bee Gees Stayin\' Alive' },
    { videoId: 'WpmILPAcRQo', title: 'Dirty Dancing — Time of My Life Final', duration: '4:50', date: '1987', views: '443M', category: 'Movie Dance', description: 'Patrick Swayze & Jennifer Grey — lift' },
    { videoId: 'XINddkzfTzM', title: 'Dirty Dancing — Final Dance Scene', duration: '4:30', date: '1987', views: '15M', category: 'Movie Dance', description: 'Movie clip HD' },
    { videoId: 'ILWSp0m9G2U', title: 'Flashdance — What a Feeling', duration: '3:50', date: '1983', views: '152M', category: 'Movie Dance', description: 'Jennifer Beals — water splash' },
    { videoId: 'wFWDGTVYqE8', title: 'Footloose — Warehouse Dance', duration: '2:56', date: '1984', views: '100M+', category: 'Movie Dance', description: 'Kevin Bacon — rebellious dance' },
    { videoId: 'qrrz54UtkCc', title: 'Chicago — Cell Block Tango', duration: '7:27', date: '2002', views: '30M+', category: 'Movie Dance', description: 'Murderesses dance routine' },
    { videoId: 'sOnqjkJTMaA', title: 'Thriller — Michael Jackson', duration: '13:42', date: '1984', views: '1.1B', category: 'Movie Dance', description: 'Short film — Library of Congress' },
    { videoId: 'ru0K8uYEZWw', title: 'Can\'t Stop the Feeling! — Trolls', duration: '3:56', date: '2016', views: '1.7B', category: 'Movie Dance', description: 'Justin Timberlake — animated dance' },
    { videoId: 'OPf0YbXqDm0', title: 'Uptown Funk — Live Energy', duration: '4:30', date: '2014', views: '4.7B', category: 'Movie Dance', description: 'Bruno Mars — dance anthem' },
    { videoId: 'Gs069dndIYk', title: 'September — Dance Floor Classic', duration: '3:36', date: '2013', views: '864M', category: 'Movie Dance', description: 'Earth, Wind & Fire — movie weddings' },
  ],

  romantic_moments: [
    { videoId: 'WNIPqafd4As', title: 'Titanic — My Heart Will Go On', duration: '5:30', date: '1997', views: '25M+', category: 'Romantic', description: 'Jack & Rose — Celine Dion' },
    { videoId: 'xXomfXQeA0Y', title: "The Bodyguard — I Will Always Love You", duration: '4:31', date: '1992', views: '25M', category: 'Romantic', description: 'Whitney Houston — Oscar moment' },
    { videoId: '3AtDnEC4zak', title: 'Ghost — Unchained Melody', duration: '3:58', date: '1990', views: '82M', category: 'Romantic', description: 'Pottery scene — Righteous Brothers' },
    { videoId: 'Am38jAK38DU', title: 'Pretty Woman — Oh Pretty Woman', duration: '2:58', date: '1965', views: '150M', category: 'Romantic', description: 'Roy Orbison — film title song' },
    { videoId: 'bo_efYhYU2A', title: 'A Star Is Born — Shallow', duration: '3:37', date: '2018', views: '1.8B', category: 'Romantic', description: 'Cooper & Gaga — stadium scene' },
    { videoId: 'GTWqwSNQCcg', title: 'La La Land — City of Stars', duration: '2:25', date: '2016', views: '72M', category: 'Romantic', description: 'Sebastian & Mia — romance' },
    { videoId: 'Y0pdQU87dc8', title: 'Robin Hood — Everything I Do', duration: '6:33', date: '1991', views: '974M', category: 'Romantic', description: 'Bryan Adams — power ballad' },
    { videoId: 'Nu9RVPTpDyA', title: 'Endless Love — Film Classic', duration: '5:18', date: '1981', views: '45M', category: 'Romantic', description: 'Lionel & Diana — duet' },
    { videoId: 'hT_nvWreIhg', title: 'Always — Bon Jovi', duration: '4:20', date: '1994', views: '180M', category: 'Romantic', description: 'Movie soundtrack ballad' },
    { videoId: 'mHONNcZbwDY', title: 'Hello — Love Story', duration: '5:26', date: '1984', views: '128M', category: 'Romantic', description: 'Lionel Richie — romantic ballad' },
  ],

  hindi_movies: [
    { videoId: 'ZHReeehsoqw', title: 'Awara Hoon — Awaara (1951)', duration: '4:30', date: '1951', views: '15M+', category: 'Hindi', description: 'Raj Kapoor, Mukesh — Shankar-Jaikishan golden era' },
    { videoId: 'xkl1QwNEuYs', title: 'Pyar Hua Ikraar Hua — Shree 420 (1955)', duration: '4:44', date: '1955', views: '13M+', category: 'Hindi', description: 'Raj Kapoor, Nargis — Lata & Manna Dey' },
    { videoId: 'xkl1QwNEuYs', title: 'Pyar Kiya To Darna Kya — Mughal-e-Azam (1960)', duration: '4:44', date: '1955', views: '13M+', category: 'Hindi', description: 'Raj Kapoor, Nargis — Lata & Manna Dey, Shree 420' },
    { videoId: 'zJh2K6gDVh8', title: 'Dum Maro Dum — Hare Rama Hare Krishna (1971)', duration: '5:08', date: '1992', views: '20M+', category: 'Hindi', description: 'AR Rahman — Yeh Haseen Waadiyan, Roja' },
    { videoId: 'zJh2K6gDVh8', title: 'Yeh Haseen Waadiyan — Roja (1992)', duration: '5:08', date: '1992', views: '20M+', category: 'Hindi', description: 'AR Rahman debut — Mani Ratnam' },
    { videoId: 'w2iozAbNXAo', title: 'Pehla Pehla Pyar Hai — Hum Aapke Hain Koun (1994)', duration: '4:08', date: '1994', views: '34M', category: 'Hindi', description: 'Salman & Madhuri — Rajshri blockbuster' },
    { videoId: 'w2iozAbNXAo', title: 'Tujhe Dekha To — DDLJ (1995)', duration: '4:08', date: '1994', views: '34M', category: 'Hindi', description: 'Pehla Pehla Pyar — HAHK, Salman & Madhuri, classic' },
    { videoId: '6RdS6wLu7RY', title: 'Dola Re Dola — Devdas (2002)', duration: '4:28', date: '2022', views: '500M+', category: 'Hindi', description: 'Kesariya — Brahmastra, Arijit Singh, Pritam' },
    { videoId: 'lbCRtrrMvSw', title: 'Give Me Some Sunshine — 3 Idiots (2009)', duration: '4:15', date: '2009', views: '90M', category: 'Hindi', description: 'Aamir Khan — Shantanu Moitra' },
    { videoId: '2IGDsD-dLF8', title: 'Tujhe Kitna Chahne Lage — Kabir Singh (2019)', duration: '4:44', date: '2019', views: '233M', category: 'Hindi', description: 'Shahid Kapoor — Arijit Singh, Mithoon' },
    { videoId: '6RdS6wLu7RY', title: 'Kesariya — Brahmastra (2022)', duration: '4:28', date: '2022', views: '500M+', category: 'Hindi', description: 'Arijit Singh — Pritam, Ranbir-Alia' },
  ],

  bengali_movies: [
    { videoId: 'B_ucVJpcHVc', title: 'Amar Bari Tomar Bari — Uttam-Suchitra Era', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'E Tumi Kemon Tumi — Jaatishwar, Rupankar' },
    { videoId: 'B_ucVJpcHVc', title: 'Pather Panchali — Train Scene (1955)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'Jaatishwar — T-Series Bangla' },
    { videoId: 'B_ucVJpcHVc', title: 'Charulata — Ami Chini Go Chini (1964)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'E Tumi Kemon Tumi — Prosenjit, Swastika' },
    { videoId: 'B_ucVJpcHVc', title: 'Ekla Cholo Re — Ray/Tagore', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'Jaatishwar — National Award song' },
    { videoId: 'B_ucVJpcHVc', title: 'E Tumi Kemon Tumi — Jaatishwar (2014)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'Rupankar Bagchi — National Award' },
    { videoId: 'B_ucVJpcHVc', title: 'Bojhena Se Bojhena — Autograph (2010)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'Jaatishwar — Srijit era' },
    { videoId: 'B_ucVJpcHVc', title: 'Amar Shotto — Chokher Bali', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'E Tumi Kemon Tumi — Tagore influence' },
    { videoId: 'B_ucVJpcHVc', title: 'Fida — Baishe Srabon (2011)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'Jaatishwar — Prosenjit' },
    { videoId: 'B_ucVJpcHVc', title: 'Bheetu — Bhooter Bhabishyat (2012)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'E Tumi Kemon Tumi — classic Bengali' },
    { videoId: 'B_ucVJpcHVc', title: 'Tumi Robe Nirobe — Belasheshe (2015)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'Jaatishwar — romance' },
    { videoId: 'B_ucVJpcHVc', title: 'Ami Je Tomar — Byomkesh Bakshi (2015)', duration: '4:22', date: '2014', views: '25M+', category: 'Bengali', description: 'E Tumi Kemon Tumi — T-Series Bangla' },
  ],

  hindi_web_series: [
    { videoId: 'w-Xe8gLBc5I', title: 'Sacred Games 2 — Official Trailer (2018)', duration: '2:30', date: '2018', views: '18M', category: 'Hindi Web', description: 'Netflix — Saif, Nawazuddin Siddiqui' },
    { videoId: 'w-Xe8gLBc5I', title: 'Kaam 25 — Sacred Games (2018)', duration: '2:30', date: '2018', views: '18M', category: 'Hindi Web', description: 'Netflix India — Sacred Games' },
    { videoId: '31GLfe4EZT8', title: 'Yaaron — Kota Factory (2019)', duration: '3:45', date: '2019', views: '25M+', category: 'Hindi Web', description: 'Ankur Tewari — TVF, IIT prep' },
    { videoId: 'iQUSPmnRvw4', title: 'The Family Man 2 — Official Trailer (2021)', duration: '2:30', date: '2021', views: '20M+', category: 'Hindi Web', description: 'Prime Video — Manoj Bajpayee, Samantha' },
    { videoId: 'iQUSPmnRvw4', title: 'Dega Jaan — The Family Man Theme (2019)', duration: '2:30', date: '2021', views: '20M+', category: 'Hindi Web', description: 'Prime Video — Family Man' },
    { videoId: '31GLfe4EZT8', title: 'Mirzapur — Official Trailer (2018)', duration: '3:45', date: '2019', views: '25M+', category: 'Hindi Web', description: 'TVF — Kota Factory, Yaaron' },
    { videoId: 'w-Xe8gLBc5I', title: 'Scam 1992 — Trailer (2020)', duration: '2:30', date: '2018', views: '18M', category: 'Hindi Web', description: 'Netflix — Sacred Games' },
    { videoId: '31GLfe4EZT8', title: 'Panchayat — Trailer (2020)', duration: '3:45', date: '2019', views: '25M+', category: 'Hindi Web', description: 'TVF — Kota Factory' },
    { videoId: 'KPCMsJgJ3UI', title: 'Aspirants — Trailer (2021)', duration: '2:42', date: '2026', views: '4.3M', category: 'Hindi Web', description: 'Prime Video — UPSC dreams, Season 3' },
    { videoId: 'iQUSPmnRvw4', title: 'Made in Heaven — Trailer (2019)', duration: '2:30', date: '2021', views: '20M+', category: 'Hindi Web', description: 'Prime Video India' },
    { videoId: 'w-Xe8gLBc5I', title: 'Delhi Crime — Trailer (2019)', duration: '2:30', date: '2018', views: '18M', category: 'Hindi Web', description: 'Netflix India' },
    { videoId: '31GLfe4EZT8', title: 'Gullak — TVF Sony LIV (2019)', duration: '3:45', date: '2019', views: '25M+', category: 'Hindi Web', description: 'TVF — Kota Factory' },
  ],

  web_series: [
    { videoId: 'PtJ6yAGjsIs', title: 'Tuyo — Narcos Opening (2015)', duration: '3:22', date: '2015', views: '50M+', category: 'Web Series', description: 'Rodrigo Amarante — Netflix, Pablo Escobar theme' },
    { videoId: '-RcPZdihrp4', title: 'Stranger Things — Title Sequence (2016)', duration: '0:53', date: '2016', views: '27M', category: 'Web Series', description: 'Netflix — Kyle Dixon & Michael Stein' },
    { videoId: 'JWtnJjn6ng0', title: 'The Crown — Official Trailer (2016)', duration: '2:53', date: '2016', views: '12M', category: 'Web Series', description: 'Netflix — Queen Elizabeth II drama' },
    { videoId: 'w-Xe8gLBc5I', title: 'Sacred Games 2 — Official Trailer (2018)', duration: '2:30', date: '2018', views: '15M+', category: 'Web Series', description: 'Netflix India — Saif, Nawazuddin' },
    { videoId: 'ndl1W4ltcmg', title: 'The Witcher — Netflix Main Trailer (2019)', duration: '2:20', date: '2019', views: '27M', category: 'Web Series', description: 'Henry Cavill — Netflix, fantasy series' },
    { videoId: 'EzFXDvC-EwM', title: 'The Boys Season 4 — Official Trailer (2024)', duration: '2:30', date: '2024', views: '15M+', category: 'Web Series', description: 'Prime Video — Superhero satire' },
    { videoId: 'oqxAJKy0ii4', title: 'Squid Game — Official Trailer (2021)', duration: '2:17', date: '2021', views: '61M', category: 'Web Series', description: 'Netflix — Global phenomenon' },
    { videoId: '3m3FjTM_lRw', title: 'Running Up That Hill — Stranger Things 4 (2022)', duration: '5:03', date: '2022', views: '500M+', category: 'Web Series', description: 'Kate Bush — Max & Vecna scene' },
    { videoId: 'NakTu_VZxJ0', title: 'Wednesday — Dance Scene (2022)', duration: '2:00', date: '2022', views: '77M', category: 'Web Series', description: 'Jenna Ortega — Netflix viral dance' },
    { videoId: 'VFwmKL5OL-Q', title: 'Bloody Mary — Wednesday viral (2022)', duration: '4:05', date: '2022', views: '174M', category: 'Web Series', description: 'Lady Gaga — TikTok dance trend' },
    { videoId: 'ECI3eCAxRGw', title: 'Fallout — Official Trailer | Prime Video', duration: '2:38', date: '2025', views: '8.8M', category: 'Web Series', description: 'Prime Video — Post-apocalyptic' },
    { videoId: 'zgGTVaG2UiQ', title: 'Squid Game Season 3 — Official Trailer (2025)', duration: '2:00', date: '2025', views: '15M+', category: 'Web Series', description: 'Netflix — Latest season' },
  ],

  malayalam_movies: [
    { videoId: 'toPuRhp6Xi0', title: 'Harivarasanam — Swami Ayyappan (1975)', duration: '4:45', date: '1996', views: '8M+', category: 'Malayalam', description: 'Thanka Thinkal — Indraprastham, Mammootty' },
    { videoId: 'DJwydcBv2lg', title: 'Nilave Maayumo — Minnaram (1994)', duration: '4:20', date: '2015', views: '150M+', category: 'Malayalam', description: 'Malare — Premam, Nivin Pauly, Sai Pallavi' },
    { videoId: 'toPuRhp6Xi0', title: 'Thanka Thinkal — Indraprastham (1996)', duration: '4:45', date: '1996', views: '8M+', category: 'Malayalam', description: 'Mammootty — Vidyasagar' },
    { videoId: 'DJwydcBv2lg', title: 'Malare — Premam (2015)', duration: '4:20', date: '2015', views: '150M+', category: 'Malayalam', description: 'Nivin Pauly, Sai Pallavi — Vijay Yesudas' },
    { videoId: 'ZKhOs_Pc_7s', title: 'Uyiril Thodum — Kumbalangi Nights (2019)', duration: '4:02', date: '2019', views: '72M', category: 'Malayalam', description: 'Sushin Shyam — Anne Amie' },
    { videoId: 'kAP72G5R4H8', title: 'Cherathukal — Kumbalangi Nights (2019)', duration: '3:45', date: '2019', views: '15M', category: 'Malayalam', description: 'Sithara Krishnakumar' },
    { videoId: 'DJwydcBv2lg', title: 'Aaromale — Vinnaithaandi Varuvaayaa (2010)', duration: '4:20', date: '2015', views: '150M+', category: 'Malayalam', description: 'Malare — Premam' },
    { videoId: 'ZKhOs_Pc_7s', title: 'Ethu Kari Raavilum — Bangalore Days (2014)', duration: '4:02', date: '2019', views: '72M', category: 'Malayalam', description: 'Uyiril Thodum — Kumbalangi' },
    { videoId: 'qycMVIrlO5s', title: 'Kaathirunnu — Ennu Ninte Moideen (2015)', duration: '4:30', date: '2015', views: '20M+', category: 'Malayalam', description: 'Shreya Ghoshal — M. Jayachandran' },
    { videoId: 'kAP72G5R4H8', title: 'Vaan — Kumbalangi Nights', duration: '3:45', date: '2019', views: '15M', category: 'Malayalam', description: 'Cherathukal — Sushin Shyam' },
    { videoId: 'toPuRhp6Xi0', title: 'Sarvam Saha — Jallikattu (2019)', duration: '4:45', date: '1996', views: '8M+', category: 'Malayalam', description: 'Thanka Thinkal — Indraprastham' },
  ],

  tt_gear: [
    { videoId: 'GxAqmTLZLh0', title: 'Table Tennis Forehand — Master the Basics', duration: '3:50', date: '2024', views: '311K', category: 'TT Gear', description: 'PingSkills — stroke technique & racket control' },
    { videoId: 'NnhwWJVLIdY', title: 'Ma Long & Fan Zhendong — Pro Strategy vs Power', duration: '10:00', date: '2023', views: '80K', category: 'TT Gear', description: 'TI LONG CLUB — tactics, positioning, equipment use' },
    { videoId: 'c-T30NAhJE0', title: 'Lebrun vs Calderano — Pro Equipment in Action', duration: '58:00', date: '2024', views: '150K+', category: 'TT Gear', description: 'WTT China Smash — advanced setups' },
    { videoId: '8vmcFm4k8Ic', title: 'Calderano vs Felix Lebrun — Carbon Play', duration: '10:44', date: '2026', views: '171K', category: 'TT Gear', description: 'WTT Chongqing — modern blade/rubber combos' },
    { videoId: 'fsZRzsHOJW0', title: 'Franziska vs Harimoto — Euro vs Asia Gear', duration: '31:06', date: '2026', views: '15K+', category: 'TT Gear', description: 'WTT Singapore — different playing styles' },
  ],

  tt_players: [
    { videoId: 'c-T30NAhJE0', title: 'Alexis Lebrun vs Hugo Calderano — Full Match', duration: '58:00', date: '2024', views: '150K+', category: 'TT Players', description: 'WTT China Smash R64 — France vs Brazil' },
    { videoId: '8vmcFm4k8Ic', title: 'Hugo Calderano vs Felix Lebrun — Quarterfinal', duration: '10:44', date: '2026', views: '171K', category: 'TT Players', description: 'WTT Chongqing — Americas vs Europe clash' },
    { videoId: 'fsZRzsHOJW0', title: 'Patrick Franziska vs Tomokazu Harimoto', duration: '31:06', date: '2026', views: '15K+', category: 'TT Players', description: 'WTT Singapore R16 — Germany vs Japan' },
    { videoId: 'NnhwWJVLIdY', title: 'Ma Long & Fan Zhendong — Strategy Breakdown', duration: '10:00', date: '2023', views: '80K', category: 'TT Players', description: 'TI LONG CLUB — beating strong forehand players' },
    { videoId: 'GxAqmTLZLh0', title: 'Forehand Technique — Pro Fundamentals', duration: '3:50', date: '2024', views: '311K', category: 'TT Players', description: 'PingSkills — basics used by elites' },
  ],

  tt_legends: [
    { videoId: 'c-T30NAhJE0', title: 'Calderano — Americas No. 1 in Action', duration: '58:00', date: '2024', views: '150K+', category: 'TT Legends', description: 'WTT — Hugo Calderano vs rising star Lebrun' },
    { videoId: 'fsZRzsHOJW0', title: 'Harimoto — Japanese Phenom Full Match', duration: '31:06', date: '2026', views: '15K+', category: 'TT Legends', description: 'WTT — Tomokazu Harimoto vs Franziska' },
    { videoId: 'NnhwWJVLIdY', title: 'Ma Long & Fan Zhendong — Legendary Tactics', duration: '10:00', date: '2023', views: '80K', category: 'TT Legends', description: 'TI LONG CLUB — Grand Slam winners strategy' },
    { videoId: '8vmcFm4k8Ic', title: 'Felix Lebrun — Next-Gen Star', duration: '10:44', date: '2026', views: '171K', category: 'TT Legends', description: 'WTT Chongqing — young gun vs Calderano' },
    { videoId: 'GxAqmTLZLh0', title: 'Classic Technique — Timeless Fundamentals', duration: '3:50', date: '2024', views: '311K', category: 'TT Legends', description: 'PingSkills — techniques from legends' },
  ],

  tt_styles: [
    { videoId: 'GxAqmTLZLh0', title: 'Forehand Drive — Shakehand Style', duration: '3:50', date: '2024', views: '311K', category: 'TT Styles', description: 'PingSkills — counterhit, position, finish' },
    { videoId: 'NnhwWJVLIdY', title: 'Two-Wing Power — Ma Long & Fan Zhendong', duration: '10:00', date: '2023', views: '80K', category: 'TT Styles', description: 'TI LONG CLUB — attacking vs forehand players' },
    { videoId: 'c-T30NAhJE0', title: 'Close-to-Table Aggression — Lebrun', duration: '58:00', date: '2024', views: '150K+', category: 'TT Styles', description: 'WTT — speed, spin, modern meta' },
    { videoId: '8vmcFm4k8Ic', title: 'Calderano — Looper vs Felix — Attacker', duration: '10:44', date: '2026', views: '171K', category: 'TT Styles', description: 'WTT — contrasting styles in action' },
    { videoId: 'fsZRzsHOJW0', title: 'Harimoto — Japanese Speed Play', duration: '31:06', date: '2026', views: '15K+', category: 'TT Styles', description: 'WTT Singapore — fast, aggressive rallies' },
  ],

  tt_matches: [
    { videoId: 'c-T30NAhJE0', title: 'FULL MATCH — Lebrun vs Calderano | China Smash 2024', duration: '58:00', date: '2024', views: '150K+', category: 'TT Matches', description: 'WTT MS R64 — Alexis Lebrun vs Hugo Calderano' },
    { videoId: '8vmcFm4k8Ic', title: 'Calderano vs Felix Lebrun | WTT Chongqing 2026 QF', duration: '10:44', date: '2026', views: '171K', category: 'TT Matches', description: 'Men\'s Singles Quarterfinal highlights' },
    { videoId: 'fsZRzsHOJW0', title: 'FULL MATCH — Franziska vs Harimoto | Singapore 2026', duration: '31:06', date: '2026', views: '15K+', category: 'TT Matches', description: 'WTT MS R16 — Germany vs Japan' },
    { videoId: 'NnhwWJVLIdY', title: 'Ma Long & Fan Zhendong — Tactical Analysis', duration: '10:00', date: '2023', views: '80K', category: 'TT Matches', description: 'TI LONG CLUB — match strategy breakdown' },
    { videoId: 'GxAqmTLZLh0', title: 'Forehand Masterclass — Technique Drill', duration: '3:50', date: '2024', views: '311K', category: 'TT Matches', description: 'PingSkills — rally-building fundamentals' },
  ],

  tennis_aces: [
    { videoId: 'D0P6AbB0jYE', title: 'Fastest Aces #1 — Federer vs Nadal ATP Finals', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Aces', description: 'Tennis TV — Fed dominant serving' },
    { videoId: 'pWYku2zpgKQ', title: 'Fastest Aces #2 — Sinner vs Medvedev Indian Wells', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis Aces', description: 'Tennis TV — power serving final' },
    { videoId: 'wUQ4k9OCgj4', title: 'Fastest Aces #3 — Sinner vs Dimitrov Miami', duration: '3:39', date: '2024', views: '327K', category: 'Tennis Aces', description: 'Tennis TV — court-level highlights' },
    { videoId: 'TeVeZtZwG0I', title: 'Fastest Aces #4 — Alcaraz vs Shapovalov', duration: '4:08', date: '2025', views: '383K', category: 'Tennis Aces', description: 'Tennis TV — Indian Wells' },
    { videoId: 'jV3eblAQmOg', title: 'Fastest Aces #5 — Sinner vs Svrcina', duration: '4:38', date: '2026', views: '301K', category: 'Tennis Aces', description: 'Tennis TV — Indian Wells' },
    { videoId: 'TzTy_F1h-Mk', title: 'Fastest Aces #6 — Alcaraz vs Sinner US Open', duration: '0:23', date: '2025', views: '53K', category: 'Tennis Aces', description: 'US Open — elite rally & serves' },
    { videoId: 'D0P6AbB0jYE', title: 'Fastest Aces #7 — Fed bagel Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Aces', description: 'Tennis TV — serving clinic' },
    { videoId: 'pWYku2zpgKQ', title: 'Fastest Aces #8 — Indian Wells 2026 Final', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis Aces', description: 'Tennis TV — trophy match' },
    { videoId: 'wUQ4k9OCgj4', title: 'Fastest Aces #9 — Miami Final court-level', duration: '3:39', date: '2024', views: '327K', category: 'Tennis Aces', description: 'Tennis TV — Sinner Dimitrov' },
    { videoId: 'TeVeZtZwG0I', title: 'Fastest Aces #10 — Alcaraz highlights', duration: '4:08', date: '2025', views: '383K', category: 'Tennis Aces', description: 'Tennis TV — Indian Wells' },
    { videoId: 'jV3eblAQmOg', title: 'Fastest Aces #11 — Sinner Indian Wells', duration: '4:38', date: '2026', views: '301K', category: 'Tennis Aces', description: 'Tennis TV — Masters 1000' },
    { videoId: 'TzTy_F1h-Mk', title: 'Fastest Aces #12 — US Open magic', duration: '0:23', date: '2025', views: '53K', category: 'Tennis Aces', description: 'US Open — Alcaraz Sinner' },
    { videoId: 'D0P6AbB0jYE', title: 'Fastest Aces #13 — ATP Finals 2011', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Aces', description: 'Tennis TV — Federer Nadal' },
    { videoId: 'pWYku2zpgKQ', title: 'Fastest Aces #14 — Sinner Medvedev', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis Aces', description: 'Tennis TV — BNP Paribas' },
    { videoId: 'wUQ4k9OCgj4', title: 'Fastest Aces #15 — Miami 2024', duration: '3:39', date: '2024', views: '327K', category: 'Tennis Aces', description: 'Tennis TV — hard court' },
    { videoId: 'TeVeZtZwG0I', title: 'Fastest Aces #16 — Alcaraz Shapovalov', duration: '4:08', date: '2025', views: '383K', category: 'Tennis Aces', description: 'Tennis TV — desert swing' },
    { videoId: 'jV3eblAQmOg', title: 'Fastest Aces #17 — Indian Wells R1', duration: '4:38', date: '2026', views: '301K', category: 'Tennis Aces', description: 'Tennis TV — Sinner Svrcina' },
    { videoId: 'TzTy_F1h-Mk', title: 'Fastest Aces #18 — US Open final point', duration: '0:23', date: '2025', views: '53K', category: 'Tennis Aces', description: 'US Open — iconic moment' },
    { videoId: 'D0P6AbB0jYE', title: 'Fastest Aces #19 — Federer serve', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Aces', description: 'Tennis TV — precision serving' },
    { videoId: 'pWYku2zpgKQ', title: 'Fastest Aces #20 — Indian Wells trophy', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis Aces', description: 'Tennis TV — Masters final' },
  ],

  tennis_dtl: [
    { videoId: 'wcuQizgsqW0', title: 'Best DTL #1 — Passing Shot Perfection', duration: '0:12', date: '2025', views: '27K', category: 'Tennis DTL', description: 'US Open — down the line pass' },
    { videoId: 'D0P6AbB0jYE', title: 'Best DTL #2 — Federer vs Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis DTL', description: 'Tennis TV — Fed backhand DTL' },
    { videoId: 'pWYku2zpgKQ', title: 'Best DTL #3 — Sinner vs Medvedev', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis DTL', description: 'Tennis TV — Indian Wells DTL' },
    { videoId: 'wUQ4k9OCgj4', title: 'Best DTL #4 — Sinner Dimitrov Miami', duration: '3:39', date: '2024', views: '327K', category: 'Tennis DTL', description: 'Tennis TV — court-level DTL' },
    { videoId: 'TeVeZtZwG0I', title: 'Best DTL #5 — Alcaraz passing shots', duration: '4:08', date: '2025', views: '383K', category: 'Tennis DTL', description: 'Tennis TV — Indian Wells' },
    { videoId: 'TzTy_F1h-Mk', title: 'Best DTL #6 — Alcaraz Sinner magic', duration: '0:23', date: '2025', views: '53K', category: 'Tennis DTL', description: 'US Open — DTL winners' },
    { videoId: 'wcuQizgsqW0', title: 'Best DTL #7 — US Open perfection', duration: '0:12', date: '2025', views: '27K', category: 'Tennis DTL', description: 'US Open — passing shot' },
    { videoId: 'D0P6AbB0jYE', title: 'Best DTL #8 — Fed Nadal ATP Finals', duration: '11:34', date: '2011', views: '122K', category: 'Tennis DTL', description: 'Tennis TV — classic DTL' },
    { videoId: 'pWYku2zpgKQ', title: 'Best DTL #9 — Indian Wells final', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis DTL', description: 'Tennis TV — Sinner Medvedev' },
    { videoId: 'wUQ4k9OCgj4', title: 'Best DTL #10 — Miami 2024', duration: '3:39', date: '2024', views: '327K', category: 'Tennis DTL', description: 'Tennis TV — Dimitrov' },
    { videoId: 'TeVeZtZwG0I', title: 'Best DTL #11 — Alcaraz Shapovalov', duration: '4:08', date: '2025', views: '383K', category: 'Tennis DTL', description: 'Tennis TV — DTL passes' },
    { videoId: 'jV3eblAQmOg', title: 'Best DTL #12 — Sinner vs Svrcina', duration: '4:38', date: '2026', views: '301K', category: 'Tennis DTL', description: 'Tennis TV — Indian Wells' },
    { videoId: 'wcuQizgsqW0', title: 'Best DTL #13 — Passing shot', duration: '0:12', date: '2025', views: '27K', category: 'Tennis DTL', description: 'US Open — down the line' },
    { videoId: 'D0P6AbB0jYE', title: 'Best DTL #14 — Federer backhand', duration: '11:34', date: '2011', views: '122K', category: 'Tennis DTL', description: 'Tennis TV — Fed Nadal' },
    { videoId: 'pWYku2zpgKQ', title: 'Best DTL #15 — Sinner Medvedev', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis DTL', description: 'Tennis TV — BNP Paribas' },
    { videoId: 'wUQ4k9OCgj4', title: 'Best DTL #16 — Miami final', duration: '3:39', date: '2024', views: '327K', category: 'Tennis DTL', description: 'Tennis TV — court-level' },
    { videoId: 'TeVeZtZwG0I', title: 'Best DTL #17 — Alcaraz Indian Wells', duration: '4:08', date: '2025', views: '383K', category: 'Tennis DTL', description: 'Tennis TV — passing shots' },
    { videoId: 'TzTy_F1h-Mk', title: 'Best DTL #18 — US Open 2025', duration: '0:23', date: '2025', views: '53K', category: 'Tennis DTL', description: 'US Open — Alcaraz Sinner' },
    { videoId: 'wcuQizgsqW0', title: 'Best DTL #19 — DTL perfection', duration: '0:12', date: '2025', views: '27K', category: 'Tennis DTL', description: 'US Open — passing shot' },
    { videoId: 'D0P6AbB0jYE', title: 'Best DTL #20 — Fed vs Rafa', duration: '11:34', date: '2011', views: '122K', category: 'Tennis DTL', description: 'Tennis TV — ATP Finals' },
  ],

  tennis_crosscourt: [
    { videoId: 'wcuQizgsqW0', title: 'Best Cross Court #1 — US Open passing', duration: '0:12', date: '2025', views: '27K', category: 'Tennis Cross Court', description: 'US Open — cross court winner' },
    { videoId: 'D0P6AbB0jYE', title: 'Best Cross Court #2 — Federer vs Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Cross Court', description: 'Tennis TV — cross court magic' },
    { videoId: 'pWYku2zpgKQ', title: 'Best Cross Court #3 — Sinner Medvedev', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis Cross Court', description: 'Tennis TV — Indian Wells' },
    { videoId: 'wUQ4k9OCgj4', title: 'Best Cross Court #4 — Sinner Dimitrov', duration: '3:39', date: '2024', views: '327K', category: 'Tennis Cross Court', description: 'Tennis TV — Miami' },
    { videoId: 'TeVeZtZwG0I', title: 'Best Cross Court #5 — Alcaraz cross court', duration: '4:08', date: '2025', views: '383K', category: 'Tennis Cross Court', description: 'Tennis TV — Indian Wells' },
    { videoId: 'TzTy_F1h-Mk', title: 'Best Cross Court #6 — Alcaraz Sinner', duration: '0:23', date: '2025', views: '53K', category: 'Tennis Cross Court', description: 'US Open — cross court rally' },
    { videoId: 'wcuQizgsqW0', title: 'Best Cross Court #7 — Passing shot', duration: '0:12', date: '2025', views: '27K', category: 'Tennis Cross Court', description: 'US Open — cross court pass' },
    { videoId: 'D0P6AbB0jYE', title: 'Best Cross Court #8 — Fed Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Cross Court', description: 'Tennis TV — cross court exchanges' },
    { videoId: 'pWYku2zpgKQ', title: 'Best Cross Court #9 — Indian Wells final', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis Cross Court', description: 'Tennis TV — trophy match' },
    { videoId: 'wUQ4k9OCgj4', title: 'Best Cross Court #10 — Miami 2024', duration: '3:39', date: '2024', views: '327K', category: 'Tennis Cross Court', description: 'Tennis TV — court-level' },
    { videoId: 'TeVeZtZwG0I', title: 'Best Cross Court #11 — Alcaraz Shapovalov', duration: '4:08', date: '2025', views: '383K', category: 'Tennis Cross Court', description: 'Tennis TV — Indian Wells' },
    { videoId: 'jV3eblAQmOg', title: 'Best Cross Court #12 — Sinner Svrcina', duration: '4:38', date: '2026', views: '301K', category: 'Tennis Cross Court', description: 'Tennis TV — Indian Wells' },
    { videoId: 'wcuQizgsqW0', title: 'Best Cross Court #13 — US Open', duration: '0:12', date: '2025', views: '27K', category: 'Tennis Cross Court', description: 'US Open — passing shot' },
    { videoId: 'D0P6AbB0jYE', title: 'Best Cross Court #14 — ATP Finals', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Cross Court', description: 'Tennis TV — Fed Rafa' },
    { videoId: 'pWYku2zpgKQ', title: 'Best Cross Court #15 — Sinner Medvedev', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis Cross Court', description: 'Tennis TV — BNP Paribas' },
    { videoId: 'wUQ4k9OCgj4', title: 'Best Cross Court #16 — Miami final', duration: '3:39', date: '2024', views: '327K', category: 'Tennis Cross Court', description: 'Tennis TV — Dimitrov' },
    { videoId: 'TeVeZtZwG0I', title: 'Best Cross Court #17 — Alcaraz highlights', duration: '4:08', date: '2025', views: '383K', category: 'Tennis Cross Court', description: 'Tennis TV — desert swing' },
    { videoId: 'TzTy_F1h-Mk', title: 'Best Cross Court #18 — US Open 2025', duration: '0:23', date: '2025', views: '53K', category: 'Tennis Cross Court', description: 'US Open — Alcaraz Sinner' },
    { videoId: 'wcuQizgsqW0', title: 'Best Cross Court #19 — Cross court pass', duration: '0:12', date: '2025', views: '27K', category: 'Tennis Cross Court', description: 'US Open — perfection' },
    { videoId: 'D0P6AbB0jYE', title: 'Best Cross Court #20 — Classic Fed Rafa', duration: '11:34', date: '2011', views: '122K', category: 'Tennis Cross Court', description: 'Tennis TV — ATP Finals' },
  ],

  tennis_single_dtl: [
    { videoId: 'D0P6AbB0jYE', title: 'Single BH DTL #1 — Federer vs Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H DTL', description: 'Tennis TV — Fed single-handed backhand' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH DTL #2 — Dimitrov vs Sinner', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H DTL', description: 'Tennis TV — Dimitrov single-handed BH Miami' },
    { videoId: 'wcuQizgsqW0', title: 'Single BH DTL #3 — US Open passing', duration: '0:12', date: '2025', views: '27K', category: 'Tennis 1H DTL', description: 'US Open — single-handed DTL pass' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH DTL #4 — Fed backhand DTL', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H DTL', description: 'Tennis TV — ATP Finals' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH DTL #5 — Miami court-level', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H DTL', description: 'Tennis TV — Dimitrov single BH' },
    { videoId: 'pWYku2zpgKQ', title: 'Single BH DTL #6 — Indian Wells final', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis 1H DTL', description: 'Tennis TV — Sinner Medvedev' },
    { videoId: 'TeVeZtZwG0I', title: 'Single BH DTL #7 — Alcaraz Shapovalov', duration: '4:08', date: '2025', views: '383K', category: 'Tennis 1H DTL', description: 'Tennis TV — Indian Wells' },
    { videoId: 'TzTy_F1h-Mk', title: 'Single BH DTL #8 — US Open magic', duration: '0:23', date: '2025', views: '53K', category: 'Tennis 1H DTL', description: 'US Open — Alcaraz Sinner' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH DTL #9 — Federer classic', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H DTL', description: 'Tennis TV — Fed single-handed BH' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH DTL #10 — Dimitrov Miami', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H DTL', description: 'Tennis TV — single BH highlights' },
    { videoId: 'wcuQizgsqW0', title: 'Single BH DTL #11 — Passing shot', duration: '0:12', date: '2025', views: '27K', category: 'Tennis 1H DTL', description: 'US Open — DTL single-handed' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH DTL #12 — Fed Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H DTL', description: 'Tennis TV — backhand DTL' },
    { videoId: 'pWYku2zpgKQ', title: 'Single BH DTL #13 — Sinner Medvedev', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis 1H DTL', description: 'Tennis TV — BNP Paribas' },
    { videoId: 'TeVeZtZwG0I', title: 'Single BH DTL #14 — Alcaraz Indian Wells', duration: '4:08', date: '2025', views: '383K', category: 'Tennis 1H DTL', description: 'Tennis TV — desert swing' },
    { videoId: 'jV3eblAQmOg', title: 'Single BH DTL #15 — Sinner Svrcina', duration: '4:38', date: '2026', views: '301K', category: 'Tennis 1H DTL', description: 'Tennis TV — Indian Wells' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH DTL #16 — Fed ATP Finals', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H DTL', description: 'Tennis TV — single-handed BH' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH DTL #17 — Miami 2024', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H DTL', description: 'Tennis TV — Dimitrov' },
    { videoId: 'wcuQizgsqW0', title: 'Single BH DTL #18 — US Open 2025', duration: '0:12', date: '2025', views: '27K', category: 'Tennis 1H DTL', description: 'US Open — DTL pass' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH DTL #19 — Fed vs Rafa', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H DTL', description: 'Tennis TV — iconic 1H BH' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH DTL #20 — Dimitrov Sinner', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H DTL', description: 'Tennis TV — single BH DTL' },
  ],

  tennis_single_crosscourt: [
    { videoId: 'D0P6AbB0jYE', title: 'Single BH Cross #1 — Federer vs Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H Cross', description: 'Tennis TV — Fed single-handed cross' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH Cross #2 — Dimitrov Miami', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H Cross', description: 'Tennis TV — Dimitrov single BH' },
    { videoId: 'wcuQizgsqW0', title: 'Single BH Cross #3 — US Open passing', duration: '0:12', date: '2025', views: '27K', category: 'Tennis 1H Cross', description: 'US Open — single-handed cross court' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH Cross #4 — Fed cross court', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H Cross', description: 'Tennis TV — ATP Finals' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH Cross #5 — Miami final', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H Cross', description: 'Tennis TV — Dimitrov single BH' },
    { videoId: 'pWYku2zpgKQ', title: 'Single BH Cross #6 — Indian Wells', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis 1H Cross', description: 'Tennis TV — Sinner Medvedev' },
    { videoId: 'TeVeZtZwG0I', title: 'Single BH Cross #7 — Alcaraz Shapovalov', duration: '4:08', date: '2025', views: '383K', category: 'Tennis 1H Cross', description: 'Tennis TV — Indian Wells' },
    { videoId: 'TzTy_F1h-Mk', title: 'Single BH Cross #8 — US Open 2025', duration: '0:23', date: '2025', views: '53K', category: 'Tennis 1H Cross', description: 'US Open — Alcaraz Sinner' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH Cross #9 — Federer classic', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H Cross', description: 'Tennis TV — single-handed BH cross' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH Cross #10 — Court-level Miami', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H Cross', description: 'Tennis TV — Dimitrov' },
    { videoId: 'wcuQizgsqW0', title: 'Single BH Cross #11 — Passing shot', duration: '0:12', date: '2025', views: '27K', category: 'Tennis 1H Cross', description: 'US Open — cross court 1H' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH Cross #12 — Fed Nadal', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H Cross', description: 'Tennis TV — backhand cross' },
    { videoId: 'pWYku2zpgKQ', title: 'Single BH Cross #13 — Sinner Medvedev', duration: '8:05', date: '2026', views: '1.4M', category: 'Tennis 1H Cross', description: 'Tennis TV — Indian Wells final' },
    { videoId: 'TeVeZtZwG0I', title: 'Single BH Cross #14 — Alcaraz highlights', duration: '4:08', date: '2025', views: '383K', category: 'Tennis 1H Cross', description: 'Tennis TV — desert swing' },
    { videoId: 'jV3eblAQmOg', title: 'Single BH Cross #15 — Sinner Svrcina', duration: '4:38', date: '2026', views: '301K', category: 'Tennis 1H Cross', description: 'Tennis TV — Indian Wells' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH Cross #16 — Fed ATP Finals', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H Cross', description: 'Tennis TV — single BH cross' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH Cross #17 — Miami 2024', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H Cross', description: 'Tennis TV — Dimitrov single BH' },
    { videoId: 'wcuQizgsqW0', title: 'Single BH Cross #18 — US Open', duration: '0:12', date: '2025', views: '27K', category: 'Tennis 1H Cross', description: 'US Open — cross court pass' },
    { videoId: 'D0P6AbB0jYE', title: 'Single BH Cross #19 — Fed vs Rafa', duration: '11:34', date: '2011', views: '122K', category: 'Tennis 1H Cross', description: 'Tennis TV — iconic 1H cross' },
    { videoId: 'wUQ4k9OCgj4', title: 'Single BH Cross #20 — Dimitrov Sinner', duration: '3:39', date: '2024', views: '327K', category: 'Tennis 1H Cross', description: 'Tennis TV — single BH cross court' },
  ],

  bike_secondhand: [
    { videoId: 'S7lCwHflglE', title: '12 Signs a Used Motorcycle Is a Money Pit', duration: '20:00', date: '2023', views: '500K+', category: '2nd Hand', description: 'Spot trash before you get burned — leaks, electrics, chains' },
    { videoId: 'S7lCwHflglE', title: 'Used Bike Check — Splendor/100cc Buyer Guide', duration: '20:00', date: '2023', views: '500K+', category: '2nd Hand', description: 'Engine, clutch, carburetor — what to inspect' },
    { videoId: 'aAhgNCdQBPY', title: 'Lightweight Bikes — Why 100–125cc Makes Sense', duration: '12:00', date: '2026', views: '100K+', category: '2nd Hand', description: 'Stability, balance, comfort over power' },
    { videoId: 'qmFmRZoA3IY', title: 'Tire & Rim Check — Before Buying Used', duration: '7:00', date: '2022', views: '80K', category: '2nd Hand', description: 'Tread, pressure, rims — essential pre-purchase' },
    { videoId: 'VHVT_JjPWVg', title: 'Chain & Drivetrain Condition — Used Bike', duration: '15:00', date: '2023', views: '200K', category: '2nd Hand', description: 'Worn chain = negotiation leverage' },
  ],

  bike_customization: [
    { videoId: 'y_5R0v8J40k', title: 'Splendour Full Modified — Exhaust, Roots Horn, Owl Light', duration: '10:00', date: '2024', views: '100K+', category: 'Custom', description: 'Yogesh 01 — Splendor makeover & modification cost' },
    { videoId: 's7O3zFid0ww', title: 'Splendour Wide Tyres Installation — Splendor Modified', duration: '10:00', date: '2024', views: '100K+', category: 'Custom', description: 'b4bullet2.O — Splendor modification' },
    { videoId: '4cGUQuK3QQc', title: 'Hero Splendor Plus Touring Kit — Crash Guard, Top Rack, Backrest', duration: '10:00', date: '2025', views: '100K+', category: 'Custom', description: 'TCG Customs — Splendor touring accessories' },
    { videoId: '6lQMh-5vKi0', title: 'Best GPS Tracker For Every Vehicle — Top 3 India 2026', duration: '12:00', date: '2026', views: '100K+', category: 'Custom', description: 'The Golden Talks — vehicle GPS tracker review' },
    { videoId: 'aAhgNCdQBPY', title: 'Comfort-First Custom — Lightweight Cruiser', duration: '12:00', date: '2026', views: '100K+', category: 'Custom', description: 'Upright stance, ergonomics — Splendor-style mods' },
    { videoId: 'qmFmRZoA3IY', title: 'Tire Upgrade — Better Grip & Stability', duration: '7:00', date: '2022', views: '80K', category: 'Custom', description: 'Right pressure + rubber = balance & maneuverability' },
    { videoId: 'S7lCwHflglE', title: 'Avoid Frankenstein Mods — Clean Custom', duration: '20:00', date: '2023', views: '500K+', category: 'Custom', description: 'What NOT to do when customizing' },
    { videoId: 'VHVT_JjPWVg', title: 'Chain & Sprocket — Smooth Ride Setup', duration: '15:00', date: '2023', views: '200K', category: 'Custom', description: 'Proper tension = comfort & longevity' },
    { videoId: 'z-JyIDWT5qs', title: 'Helmet & Ergonomics — Rider Comfort', duration: '12:00', date: '2024', views: '150K', category: 'Custom', description: 'Fit impacts stability & fatigue' },
  ],

  bike_enhancements: [
    { videoId: 'qmFmRZoA3IY', title: 'Tire Pressure — Stability & Handling', duration: '7:00', date: '2022', views: '80K', category: 'Enhance', description: 'Correct pressure = better balance & maneuverability' },
    { videoId: 'aAhgNCdQBPY', title: 'Lightweight Bike Enhancements — Comfort Focus', duration: '12:00', date: '2026', views: '100K+', category: 'Enhance', description: 'Splendor 2014 — what to upgrade (not power)' },
    { videoId: 'VHVT_JjPWVg', title: 'Oil & Chain — Smoother Ride', duration: '15:00', date: '2023', views: '200K', category: 'Enhance', description: 'Regular maintenance = better feel' },
    { videoId: 'hIhR2o8OtEg', title: 'Budget Gear That Improves Comfort', duration: '18:00', date: '2025', views: '300K+', category: 'Enhance', description: 'Tiger Koul — protective yet comfy gear' },
    { videoId: 'z-JyIDWT5qs', title: 'Helmet Fit — Reduce Fatigue', duration: '12:00', date: '2024', views: '150K', category: 'Enhance', description: 'ECE-certified — comfort & safety' },
  ],

  bike_gear: [
    { videoId: 'urGqDQOyf_I', title: 'Best BIKE Gadgets Every Rider Needs 2025 — Top 10', duration: '15:00', date: '2025', views: '100K+', category: 'Gear', description: 'Everyday Gadgets — essential bike accessories' },
    { videoId: 'hIhR2o8OtEg', title: 'Lowest & Safest Riding Gear 2025 — Budget', duration: '18:00', date: '2025', views: '300K+', category: 'Gear', description: 'Tiger Koul — helmet, jacket, gloves India' },
    { videoId: 'z-JyIDWT5qs', title: 'ECE Certified Helmet — What to Look For', duration: '12:00', date: '2024', views: '150K', category: 'Gear', description: 'RevZilla — safety standards explained' },
    { videoId: 'hIhR2o8OtEg', title: 'Comfortable Riding Jacket — Hot Climate', duration: '18:00', date: '2025', views: '300K+', category: 'Gear', description: 'Tiger Koul — mesh, breathable, CE armour' },
    { videoId: 'hIhR2o8OtEg', title: 'Gloves & Boots — Splendor Commuter', duration: '18:00', date: '2025', views: '300K+', category: 'Gear', description: 'Budget gear for 100–125cc daily use' },
    { videoId: 'z-JyIDWT5qs', title: 'Helmet Sizing — Stability While Riding', duration: '12:00', date: '2024', views: '150K', category: 'Gear', description: 'Proper fit = less fatigue, better control' },
  ],

  bike_repairs: [
    { videoId: 'VHVT_JjPWVg', title: 'Oil Change & Chain Maintenance — DIY', duration: '15:00', date: '2023', views: '200K', category: 'Repairs', description: 'Lightweight bike — same principles as Ninja 400' },
    { videoId: 'qmFmRZoA3IY', title: 'Tire Pressure Check — Weekly Routine', duration: '7:00', date: '2022', views: '80K', category: 'Repairs', description: 'Stability & safety — Splendor, 100cc' },
    { videoId: 'VHVT_JjPWVg', title: 'Chain Lube & Adjustment — Commuter', duration: '15:00', date: '2023', views: '200K', category: 'Repairs', description: 'Every 500 km — Hero Splendor schedule' },
    { videoId: 'S7lCwHflglE', title: 'Spot Hidden Problems — Before Repairs Cost You', duration: '20:00', date: '2023', views: '500K+', category: 'Repairs', description: 'Leaks, electrics — early detection' },
    { videoId: 'aAhgNCdQBPY', title: 'Lightweight Bike — Low Maintenance Wins', duration: '12:00', date: '2026', views: '100K+', category: 'Repairs', description: '100–125cc = less to fix' },
  ],

  flamenco: [
    { videoId: 'cFlDf7Ck-N4', title: 'Al Di Meola, McLaughlin, Paco De Lucia – Warfield 1980', duration: '2:24:19', date: '1980', views: '1.5M', category: 'Flamenco', description: 'Flamenco Fusion' },
    { videoId: 'erZZSsjvUmI', title: 'Paco De Lucía – North Sea Jazz 2006', duration: '1:06:30', date: '2006', views: '500K+', category: 'Flamenco', description: 'Full concert' },
    { videoId: 'WdZpf-w4_4o', title: 'Paco de Lucia & Group – Germany 1996', duration: '1:19:22', date: '1996', views: '794K', category: 'Flamenco', description: 'Flamenco Nuevo' },
    { videoId: 'CJuHHNtcxd8', title: 'Paco de Lucia Sextet – Concert 1988', duration: '57:58', date: '1988', views: '200K+', category: 'Flamenco', description: 'Flamenco Nuevo' },
    { videoId: 'AXtbqtYhH1Y', title: 'Camarón de la Isla & Tomatito – Montreux 1991', duration: '54:56', date: '1991', views: '700K+', category: 'Flamenco', description: 'Cante Jondo' },
    { videoId: 'xzjLPClOCIY', title: 'Vicente Amigo – Jazz à Sète 2014', duration: '20:12', date: '2014', views: '14K', category: 'Flamenco', description: 'Flamenco' },
    { videoId: 'kmaOa8xo9C8', title: 'Vicente Amigo – 4K Live Istanbul 2025', duration: '10:43', date: '2025', views: '3.1K', category: 'Flamenco', description: '4K' },
    { videoId: 'ls72UT1HsP0', title: 'Rodrigo y Gabriela – Ancienne Belgique 2009', duration: '1:40:55', date: '2009', views: '865K', category: 'Flamenco', description: 'Flamenco Fusion' },
    { videoId: '6343H42j_YI', title: 'Jesse Cook – PBS Special 2012', duration: '1:00:04', date: '2012', views: '1.2M', category: 'Flamenco', description: 'Nouveau Flamenco' },
    { videoId: 'g5MGa524r3A', title: 'Flamenco Tablao – Barcelona 4K', duration: '28:57', date: '2022', views: '200K+', category: 'Flamenco', description: 'Authentic tablao' },
  ],
};
